### ISSUE TITLE
remove mtls attribute for Tcp mixer filter

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#1032]
TLS is application layer protocol.  Tcp mixer filter only deal with Tcp connection.  At connection creation time, there is not mTLS yet.  So it will be always false for tcp filer.  

So please remove it.

**Comment by qiwzhang** [comment]
@lei-tang Thanks for bringing this up

**Comment by JimmyCYJ** [comment]
Mixer needs connection.mtls attribute in Check() call to decide whether a connection should be rejected. 
I think only TCP filter can close a connection per Check() call.

+@mandarjog
