### ISSUE TITLE
response.code attribute may use un-initialized value

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#1126]
response.code sometime seen as very big value.

It is possible that it is not initialized.

The code is here

https://github.com/istio/mixerclient/blob/master/control/src/http/attributes_builder.cc#L140

**Comment by mandarjog** [comment]
https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc#L332

Here is where value is conditionally set.
