### ISSUE TITLE
Mixer client should Report check.cache_hit, quota.cache_hit attributes

### ISSUE THREAD

**Issue by mandarjog** [istio/proxy#1181]
Mixer client has access to this information but does not include it in the report call.

If included it can be added as dimension to metrics.

Also rename
`check.error_code`  to `mixer.check_status`

That way all present and future mixer info is in the `mixer.*` namespace.

**Comment by qiwzhang** [comment]
as discussed,  error_code and error_message remains under "check" namespace.  We may have authz check and other types of check in addition to mixer check.  They are called "check".

two more bool attributes will be added in the report:

check.cache_hit
quota.cache_hit.

**Comment by qiwzhang** [comment]
@mandarjog  how about we create a new name space "cache_hit".  It will have format as

cache_hit.COMPONENT.CALL.   

COMPONENT could be mixer_client,  mixer_adaptor,  and etc.
CALL could be check,  quota. 

So mixer client will add

cache_hit.mixer_client.check
cache_hit.mixer_client.quota

Or we can call it

cache_hit.CALL.COMPONENT

cache_hit.check.mixer_client
cache_hit.quota.mixer_client
