### ISSUE TITLE
istio/istio proxy's sha is 13 days old

### ISSUE THREAD

**Issue by ldemailly** [istio/proxy#1190]
we are soon going to enter 0.7 stabilization, we need the latest fixes in sooner than later

any idea why the sha is stuck in the past ?

istio/istio.Version:

80ec4f6c2a672b00e55d34ef9b5d26a42a98da42

(which btw costin wants to roll back to 54077a0c8486b6db7b2fc5d10619b6813bb40767 )

also why is your build broken for so long ?

**Comment by JimmyCYJ** [comment]
I think the auto update is disabled. I will manually update proxy's sha and re-enable the auto update bot.
