### ISSUE TITLE
Mixer client needs retry behavior

### ISSUE THREAD

**Issue by geeknoid** [istio/proxy#1192]
@geeknoid commented on [Thu Mar 08 2018](https://github.com/istio/mixerclient/issues/439)

Mixer client needs retry semantics around all calls to Mixer.

---

@ldemailly commented on [Thu Mar 08 2018](https://github.com/istio/mixerclient/issues/439#issuecomment-371605967)

reminder: this repo is dead (you reviewed the diff that moved the code to proxy)

**Comment by kyessenov** [comment]
This is done since mixer upstream is just a regular service.
