### ISSUE TITLE
Use an uniform tagging system across all docker istio images (manager, mixer, proxy)

### ISSUE THREAD

**Issue by andraxylia** [istio/proxy#121]
Build system (jenkins/travis) applies:

1.  "date+build#" , where date is YYYY-MM-DD-HH:SS ; required on all images
      - date is a must giving Bazel build produces incorrect date
      - build# - keep in mind that Mixer is on travis, manager + proxy + app (runtime) are on Jenkins

2.  short SHA - required on all images
      github search repo with short SHA will find the commit directly, no need to go to the build system as an extra step

3.  "latest":  to be used only by the build system, only if we apply it explicitly and force it with any new push, otherwise we fall in this trap http://container-solutions.com/docker-latest-confusion/
only one image per repo will have this label

4.  "alpha-XX.XX" 
optional, same label used for all repos, so we can select a matching set of images
can become beta etc.

5.  "release-XX.XX" for when time comes :)

Private builds:

1.  username + date , where date is YYYY-MM-DD-HH:SS - this will help clean up stale images

For all types of builds, additional manual labels are permitted, for instance "demo", "featureX-working". There is virtually no penalty for using multiple labels on an image.

**Comment by sebastienvas** [comment]
Thanks Andra. Do you know who created the docker hub for istio ?

**Comment by andraxylia** [comment]
I do not know.

**Comment by kyessenov** [comment]
@rshriram I think.

**Comment by rshriram** [comment]
I did. And I think you guys have admin perms to add Sebastian

**Comment by andraxylia** [comment]
Sebastien, you are already added:

https://hub.docker.com/u/istio/dashboard/teams/?team=owners

**Comment by sebastienvas** [comment]
Yes thanks! With Jason we've update Manager to push images to docker hub.
Will update other modules later.

**Comment by andraxylia** [comment]
Great, thank you!

Andra

**Comment by qiwzhang** [comment]
Jenkins Postsubmit test is already doing this.
