### ISSUE TITLE
envoy.conf.template cannot be parsed by the latest Envoy

### ISSUE THREAD

**Issue by andraxylia** [istio/proxy#1210]
This file cannot be parsed by the latest envoy:
https://github.com/istio/proxy/blob/master/src/envoy/http/mixer/envoy.conf.template

As a result, start_envoy script does not work.

start_envoy should be part of istio/proxy pre-submit, it should not fail in istio/istio.

See more in istio/istio#4292

[envoy.conf.txt](https://github.com/istio/proxy/files/1817940/envoy.conf.txt)
[start_envoy_output.txt](https://github.com/istio/proxy/files/1817941/start_envoy_output.txt)

**Comment by ldemailly** [comment]
inlining the error to not have to download files and open them:
```
[2018-03-15 21:25:28.259][215794][debug][main] external/envoy/source/server/server.cc:164] Unable to initialize config as v2, will retry as v1: Unable to parse JSON as proto (INVALID_ARGUMENT:cluster_manager: Cannot find field.): {
  "listeners": [
```
