### ISSUE TITLE
Create AuthN filter to perform authentication.

### ISSUE THREAD

**Issue by diemtvu** [istio/proxy#1214]
The filter config should contain the peer/origin/principal logic as described by the policy (in the early version, it could be the original policy itself). 

The filter will be put behind 'validation' filters (e.g Jwt), which are responsible to verify certificate and extract claims. It will simply consume the output from those filters (which are stored in request header), and follow credential logic from policy to construct request principal (or reject request if data missing, per policy spec).

Parent issue: https://github.com/istio/istio/issues/1948

**Comment by diemtvu** [comment]
https://github.com/istio/proxy/pull/1170
https://github.com/istio/proxy/pull/1171
https://github.com/istio/proxy/pull/1204
https://github.com/istio/proxy/pull/1209

**Comment by lei-tang** [comment]
PR https://github.com/istio/proxy/pull/1216 is created for this issue.
