### ISSUE TITLE
Migrate "v2" config to "v1" in Mixer fitler config

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#1217]
Currently,  it is using "v2" which is confusing.   Decided to migrate it back to "v1" with following steps

1) change proxy to support both "v1" and "v2" fields.  if this is version x
2) After that is widely deployed,  change Pilot to "s/v2/v1", also release node that side-car proxy has to be at lease version x.  Please fiile an issue in istio.
3) after a while, remove "v2" in the proxy.

**Comment by JimmyCYJ** [comment]
When this change is in Proxy release, I will file an issue for Pilot to update Mixer filter config.
