### ISSUE TITLE
Use StopIterationAndWatermark instead of StopIterationAndBuffer

### ISSUE THREAD

**Issue by lizan** [istio/proxy#1315]
https://github.com/envoyproxy/envoy/issues/2919
https://github.com/istio/istio/issues/4271

**Comment by lizan** [comment]
@JimmyCYJ can you take a look?

**Comment by lizan** [comment]
The difference between them: https://github.com/envoyproxy/envoy/pull/1417/files#diff-e86e2fdda1803a5dc62b6a9bd3ba6cee

**Comment by linsun** [comment]
Yes, it certainly buffers too much today.  We should only buffer when it is really needed imho... in my case (see scenario in https://github.com/envoyproxy/envoy/issues/2919), I'm not even using mixer policy enforcement so I would not expect this to impact me.  Also, @matt Klein suggested to "buffer level to some amount that is mostly safe to account for service latency." -- I think we should look into if the default buffer level is good for us.

**Comment by lizan** [comment]
Envoy introduced `StopIterationAndWatermark` in September, which applies back pressure to downstream, `StopIterationAndBuffer` is the only choice before then. Once we migrated to `StopIterationAndWatermark` the buffer should be adjusted accordingly, none of istio filters need buffer data since we do not investigate each data frames.

**Comment by JimmyCYJ** [comment]
Thanks for the investigation, Lizan! I will work on the migration.

**Comment by linsun** [comment]
Cool, is StopIterationAndWatermark avail in envoy v1 or we need to move to v2?

**Comment by lizan** [comment]
It is filter internal thing and has nothing to do with v1 vs v2.
