### ISSUE TITLE
proxy-postsubmit occasionally fails due to server crash 

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/proxy#1323]
https://prow.istio.io/?repo=istio%2Fproxy&job=proxy-postsubmit occasionally fails with this error log
"Server crashed during startup". When it happens, we need to manually restart proxy-postsubmit.

We need to figure out why server crashes during startup, and fix this issue.

**Comment by JimmyCYJ** [comment]
cc @sebastienvas

**Comment by sebastienvas** [comment]
I also update the build pool with nodes with higher mem and cpu
