### ISSUE TITLE
Remove internal headers used to pass data between filters 

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#1363]
From  jwt_authn:  we use "forward_payload_header" for each JWT token to forward Jwt Payload to istio_authn filter.

istio_authn should remove these headers.

from istio_authn filter, we use "sec-istio-authn-payload" to pass results to mixer filter.

mixer fitler should remove this header.

**Comment by lei-tang** [comment]
I am implementing a PR for this issue.

**Comment by diemtvu** [comment]
#1364 might not cover all cases.

**Comment by diemtvu** [comment]
Reject requests still being logged (mixer). We don't want the log contains internal data between filters. + @qiwzhang
