### ISSUE TITLE
gRPC <-> JSON/REST Transcoding

### ISSUE THREAD

**Issue by jasminejaksic** [istio/proxy#163]

**Comment by lizan** [comment]
Also tracked here: https://github.com/lyft/envoy/issues/501

**Comment by lizan** [comment]
Implemented in https://github.com/istio/proxy/tree/master/src/envoy/transcoding

**Comment by HPrinz** [comment]
> Implemented in https://github.com/istio/proxy/tree/master/src/envoy/transcoding

This link is broken. The envoy grpc-json transcoder filter can be found here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter?
