### ISSUE TITLE
ci: very slow builds

### ISSUE THREAD

**Issue by kyessenov** [istio/proxy#1815]
circleci takes > 40 minutes to run pre-submit, while prow takes about 15-20 minutes.
Can something be done to make circle faster or not make it required?

**Comment by mandarjog** [comment]
I just complained about prow pre-submits ...
https://k8s-gubernator.appspot.com/builds/istio-prow/directory/istio-presubmit

Almost 30 mins each...

**Comment by kyessenov** [comment]
This is for proxy. Example https://circleci.com/gh/istio/proxy/2281?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Note that prow on istio takes long mostly because of the dependency on a real cluster.

**Comment by hklai** [comment]
@mandarjog that job builds images and push to GCR. They are time consuming.

@kyessenov circle builds deb (make deb BAZEL_BUILD_ARGS="-j 4") but it does not look like prow is doing the same thing.
https://storage.googleapis.com/istio-prow/pull/istio_proxy/1814/proxy-presubmit/1869/build-log.txt

**Comment by kyessenov** [comment]
Is anyone actually using that deb rule? Can't that be done in istio/istio? It looks like a thin wrapper over bazel, which means prow could easily do it as well.

**Comment by hklai** [comment]
No idea. Perhaps @costinm or @rshriram set that up some time ago?

**Comment by kyessenov** [comment]
Can something be done about this? What's the purpose of circle CI when it is twice as slow as prow and not adding anything extra?

**Comment by hklai** [comment]
I can't speak for circle, but we have a plan to experiment using local docker registry in these tests (instead of relying on GCR) to speed up prow E2E tests (and eliminate the need for pushing to GCR which takes a substantial amount of time ).

**Comment by kyessenov** [comment]
This is istio/proxy :) It's an opposite problem here, circle is twice as slow with no clear benefit.

**Comment by PiotrSikora** [comment]
@kyessenov it's slow, because `circleci/build` is running all 3 tests in 1 target (`make test`, `make test_asan` and `make test_tsan`), whereas prow tests are running them in separate targets.

I don't know the reasoning behind that... perhaps it was originally running on free quota?

**Comment by kyessenov** [comment]
I'm sure this is fixable, I just want whoever installed circle, made it mandatory, and left, to take care of it.
