### ISSUE TITLE
Need Document of what enhancement Istio proxy provided comparing to  pure envoy

### ISSUE THREAD

**Issue by rokii** [istio/proxy#1830]
We have adopted Lyft Envoy as proxy for TLS. And we have agent to manage the Envoy process.
When migrating to Istio service mesh for VM expansion case, we want to know the gaps if we are keeping original Envoy as the sidecar .

**Comment by kyessenov** [comment]
Envoy is by design fairly modular. Istio proxy just adds several filters on top of vanilla envoy:
https://github.com/istio/proxy/tree/master/src/envoy

If you don't need features enabled by these filters (ALTS, mixer, JWT), then feel free to use vanilla envoy.

**Comment by rokii** [comment]
thx!
