### ISSUE TITLE
Open connection.event will not be reported

### ISSUE THREAD

**Issue by bianpengyuan** [istio/proxy#1835]
Though three connection events are added by https://github.com/istio/proxy/pull/1371, connection `open` event will never be reported.

With current logic `open` is recorded when check is called for a TCP connection. However report won't be called until either periodic report triggered or connection closing, which rewrites connection event to either `continue` or `close`. 

Should we make a report call at onNewConnection?

@qiwzhang @JimmyCYJ

**Comment by qiwzhang** [comment]
I am OK to send a report when tcp connection is open.  It should not be a blocking call (the connection should not wait for its response), and it will be batched anyway.
