### ISSUE TITLE
could envoy load JWT token(like k8s secret for example) and inject JWT token into request if it hasn't?

### ISSUE THREAD

**Issue by wangyf2010** [istio/proxy#1840]
envoy could do authn & auth, that's good.
While as for client, could envoy load & inject JWT token into request? It might could load JWT token from k8s secret for example.

I asking this question: because currently, our app get JWT token and inject JWT into request header by itself. And server side, app verify JWT token. While that could be done by envoy totally I think.
Any comments?

**Comment by qiwzhang** [comment]
It is not clear if this is a question for Envoy or for Istio.  If it is for Envoy, it is better asked in Envoy official repo. 
I think neither Envoy nor Istio supports the requested feature (injecting JWT token into a request).  You may have to write your own HTTP filter to do that.

**Comment by qiwzhang** [comment]
If you are using Istio/Mixer, you can try this idea.  https://github.com/istio/proxy/issues/1983
