### ISSUE TITLE
JWT test failures in Istio Proxy

### ISSUE THREAD

**Issue by namrata-ibm** [istio/proxy#1841]
I have built Proxy from source on a big endian system. While running tests I am facing below failures:
```
//src/envoy/http/jwt_auth:jwt_test
//src/envoy/http/jwt_auth:jwt_authenticator_test  
```  
This seems to be happening because of failure in 'EVP_PKEY_verify' function from BoringSSL.
Unfortunately BoringSSL is not supported on big endian systems yet. 
Is there a way to bypass BoringSSL and use system OpenSSL instead, in Proxy?
Any pointers would be really helpful.

**Comment by qiwzhang** [comment]
Hi @PiotrSikora I think the right approach is to fix BorringSSL to support big endian system.  How easy is it?  Otherwise we may need a compiler flag to switch SSL.

**Comment by PiotrSikora** [comment]
BoringSSL is little-endian only, and I don't believe there are any plans to add support for big-endian systems. cc @davidben @agl

**Comment by agl** [comment]
BoringSSL is little-endian only. 

Additionally, I don't believe that, for the vast majority of projects, supporting the s390 (which is probably the context here?) is positive on a cost/benefit basis. I can understand why IBM wish to make their hardware as useful as possible by porting things, but it's far less clear that that the costs for the projects being ported are worthwhile.

**Comment by qiwzhang** [comment]
Actually, you can ignore these test failures provided that
1) you don't use JWT for istio end-user authentication. 
2) you don't make code change in Jwtauthn folder.

**Comment by namrata-ibm** [comment]
Thank you @qiwzhang. 
These 2 are among the 7 failures we are facing. It would be really helpful if you could comment on below 5 tests which are failing too:
```
1. //src/envoy/http/jwt_auth:http_filter_integration_test
2. //src/envoy/http/authn:authenticator_base_test
3. //src/envoy/http/authn:authn_utils_test
4. //src/envoy/http/authn:http_filter_integration_test
5. //src/istio/mixerclient:referenced_test  (This one is due to BoringSSL again)
```

**Comment by qiwzhang** [comment]
For Istio,  5) test is important.  It is testing mixer check cache.  If it fails,  it means check cache may mis-behave.  Unless you disable check cache.

For other 4 tests, as long as you don't use JWT in your requests, it is fine.

**Comment by PiotrSikora** [comment]
I'm pretty sure that more things than `EVP_PKEY_verify()` will fail and/or misbehave on big-endian systems, even if some of the tests are passing, so I'd recommend against using Istio Proxy or even Envoy itself on such systems.

**Comment by namrata-ibm** [comment]
Thank you for inputs.
Just wanted to know whether there is any alternative for authentication? other than JWT?

**Comment by qiwzhang** [comment]
You can use mutual TLS for authentication.   Please check out the Istio security document for details.

**Comment by namrata-ibm** [comment]
Sure, Thanks a lot Wayne for all the help :)
Closing this issue for now.
