### ISSUE TITLE
TCP weighted routing is not support in Envoy

### ISSUE THREAD

**Issue by x15zhang** [istio/proxy#1903]
Currently, only one destination is allowed for TCP services for Istio 1.0. When TCP weighted routing support is introduced in Envoy, multiple destinations with weights can be specified.
Is there any plan for TCP weighted routing support in Envoy?

**Comment by qiwzhang** [comment]
You mean supporting tcp weighted route in Istio?  is that right?   
For Istio routing issue,  could you open it in istio/istio repo?  Thanks.
