### ISSUE TITLE
Do not pass "Authorization" header to Mixer

### ISSUE THREAD

**Issue by liminw** [istio/proxy#1905]
Proxy today passes all request headers to Mixer. Since "authorization" header contains JWT credential, for security reason, we should remove it from the list of headers passed to Mixer.

**Comment by liminw** [comment]
@qiwzhang

**Comment by kyessenov** [comment]
Shouldn't JWT filter scrub it instead? This should not depend on whether or not mixer filter is present.

**Comment by liminw** [comment]
My understanding is, JWT filter has the option of whether or not to send JWT to the application, but Mixer filter always has the full set of headers. @qiwzhang, can you confirm?

**Comment by liminw** [comment]
@kyessenov but you made a good point. I agree that JWT filter should be responsible for removing the authorization header.

**Comment by qiwzhang** [comment]
Since JWT filter is in front of mixer filter,  if JWT filter remove it,  mixer filter will not see it.  So @kyessenov suggestion is valid,  users can config JWT config to remove it. 

Here is the flag <https://github.com/istio/api/blob/master/envoy/config/filter/http/jwt_auth/v2alpha1/config.proto#L157>
the default is not to forward it.

So we are good.

**Comment by qiwzhang** [comment]
It is difficult for mixer filter to  remove token too.  token can be other places than Authorization header. Mixer client needs to parse JWT config to remove them.

**Comment by liminw** [comment]
My understanding is, the JWT is targeted for the application, so it is ok for the application to consume it. But Mixer is Mesh level control panel. If, say, an admin wants to log http headers for all services in the mesh, he can do that. Then JWT will appear on Stackdriver UI. That's not desired. 

@qiwzhang Authorization header is the most common use case. We can just address that.

**Comment by kyessenov** [comment]
cc @mandarjog @geeknoid

**Comment by jboeuf** [comment]
+1 for what Limin said. From a security perspective, it is fine to have the application consume the JWT (that's kind of what it was targeted for in the first place). On the other hand, having externally usable credentials in logs is a big problem. Everyone who has access to the logs is able to replay these tokens to impersonate the customers of all services.

**Comment by kyessenov** [comment]
OK. If the requirement is not to expose `request.headers['Authorization']` to any upstream logging system ever, then it makes sense to erase it either in the proxy or in Mixer as a first pass. It seems that this should be unconditional even if Mixer requires k8s RBAC-level permissions to select which attributes are exposed to the logging system.

**Comment by qiwzhang** [comment]
OK, the action item is to remove Authorization header when sending to Mixer.

**Comment by qiwzhang** [comment]
https://github.com/istio/proxy/pull/1908

**Comment by kyessenov** [comment]
We have authorization adapters (Apigee) that need access to authentication tokens (API keys, for example). I think we should not remove them from Check calls but only scrape them in Report calls.

@jboeuf Is your concern mostly about logging (telemetry), or does it also apply to Check calls?
Is it OK to remove the header on Mixer side instead?

**Comment by jboeuf** [comment]
My concern is mainly for telemetry / logging (a potentially big number of humans having access to auth tokens in logs).

For authorization adapters, I would much prefer for the authentication to be done on the proxy and that information being sent out (without the original auth token) to the mixer's authorization checks but I understand that this may be a disruptive change in the short term so I'm OK not filtering the security sensitive headers for check calls for now.

Does that help?
