### ISSUE TITLE
Proxy fails to receive CDS

### ISSUE THREAD

**Issue by diemtvu** [istio/proxy#1911]
Using the new proxy build in Istio, I get 503 errors for all request. After a little debug, looks like it was not able to get the CDS from pilot, hence getting error like this:

```
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:Cluster not available
```

I think it starts breaking after  https://github.com/istio/proxy/pull/1894

**Comment by kyessenov** [comment]
Pilot had a race condition that removed clusters from envoy.
