### ISSUE TITLE
Unexpected caching behaviour in policy checking

### ISSUE THREAD

**Issue by domwong** [istio/proxy#1930]
Istio Proxy Version: gcr.io/istio-release/proxyv2:1.0.0

## Summary
The caching behaviour for policy checks is unexpected (or perhaps not well documented). Responses to policy checks are cached by the mixer client but it seems like the key on which responses are cached is based only off certain attributes of the request. 

I have a k8s cluster with Istio and an [OPA](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/opa/) adapter for policy checks. Given two curl commands
```
curl -H "Host:httpbin.example.com" -H "foo: bar" http://$INGRESS_HOST:$INGRESS_PORT/status/200 --verbose 
```
```
curl -H "Host:httpbin.example.com" -H "foo: baz" http://$INGRESS_HOST:$INGRESS_PORT/status/200 --verbose 
```

It appears that the policy response from the first curl request is used for the second response. If I have an OPA policy based on the value of the `foo` request header this is obviously undesirable. For example, if the first request results in an "approve" from the OPA engine the second request will be approved using the cached response even if it should be "denied".

Looking more closely at the mixer code it appears that the key for the cache is calculated [here](https://github.com/istio/proxy/blob/master/src/istio/mixerclient/referenced.cc#L201) and is based off only "well known" properties of the request. 

The caching logic is fairly complex so I've not created a PR for this (sorry) and it might be that I've misunderstood how this *should* work anyway.

## Repro

Test code to reproduce behaviour (add to `src/istio/mixerclient/check_cache_test.cc`)

```
TEST_F(CheckCacheTest, TestTwoRequestHeaderMaps) {
  CheckResponse denied_response;
  denied_response.mutable_precondition()->set_valid_use_count(1000);
  denied_response.mutable_precondition()->mutable_status()->set_code(Code::PERMISSION_DENIED);
  auto match = denied_response.mutable_precondition()
                   ->mutable_referenced_attributes()
                   ->add_attribute_matches();
  match->set_condition(ReferencedAttributes::EXACT);
  match->set_name(15);  // request.headers is used.

  Attributes attributes1;
  utils::AttributesBuilder(&attributes1)
          .AddStringMap("request.headers", {{"source.ip", "foo"}, {"foo", "baz"}});

  CheckCache::CheckResult result;
  cache_->Check(attributes1, &result);
  EXPECT_FALSE(result.IsCacheHit());

  result.SetResponse(Status::OK, attributes1, denied_response);
  EXPECT_ERROR_CODE(Code::PERMISSION_DENIED, result.status());

  // Cached response is used.
  CheckCache::CheckResult result1;
  cache_->Check(attributes1, &result1);
  EXPECT_TRUE(result1.IsCacheHit()); 

  Attributes attributes2;
  utils::AttributesBuilder(&attributes2)
      .AddStringMap("request.headers", {{"source.ip", "foo"}, {"foo", "bar"}});

  // Not in the cache since it has different value
  CheckCache::CheckResult result2;
  cache_->Check(attributes2, &result2);
  EXPECT_FALSE(result2.IsCacheHit());

  CheckResponse ok_response;
  ok_response.mutable_precondition()->set_valid_use_count(1000);
  auto match2 = ok_response.mutable_precondition()
                   ->mutable_referenced_attributes()
                   ->add_attribute_matches();
  match2->set_condition(ReferencedAttributes::EXACT);
  match2->set_name(15);  // request.headers is used.
  // Store the response to the cache
  result2.SetResponse(Status::OK, attributes2, ok_response);
  EXPECT_OK(result2.status());

  // Now it should be in the cache.
  CheckCache::CheckResult result3;
  cache_->Check(attributes2, &result3);
  EXPECT_TRUE(result3.IsCacheHit());
  EXPECT_OK(result3.status());

  // Also make sure key1 still in the cache
  CheckCache::CheckResult result4;
  cache_->Check(attributes1, &result4);
  EXPECT_TRUE(result4.IsCacheHit());
  EXPECT_ERROR_CODE(Code::PERMISSION_DENIED, result4.status());
}
```

**Comment by qiwzhang** [comment]
Thanks for your test.  I created a PR to check it in.

The problem with your test is:  request.headers is a string map type,  you have to specify map_key <https://github.com/istio/api/blob/master/mixer/v1/check.proto#L141> to indicate which map keys are used for cache.   If you are not specified,  the default value is index 0 which is "source.ip" from the global dictionary <https://github.com/istio/api/blob/master/mixer/v1/global_dictionary.yaml>.

Please make sure mixer code specified map_key in its CheckResponse.

**Comment by domwong** [comment]
Thanks for the info @qiwzhang 

So if I understand correctly there is no support for request headers which aren't in the global dictionary? e.g. given these two curl requests 

```
curl -H "Host: httpbin.example.com" -H "foo: bar" http://$INGRESS_HOST:$INGRESS_PORT/status/200 --verbose 
curl -H "Host: httpbin.example.com" -H "foo: baz" http://$INGRESS_HOST:$INGRESS_PORT/status/200 --verbose 
```

They will look the same to the proxy's `CheckCache` because the request header `foo` is not in the global dictionary and thus both requests resolve to the same cache key? Or in other words, the only request headers that can be used to uniquely identify a request for policy checking purposes are the ones that appear in the global list.

**Comment by domwong** [comment]
BTW I should add, if I change my test to well known request headers found in the global dictionary and set the `map_key` then it passes the test. So my main issue now is how to make this work for request headers not found in the global dictionary.

**Comment by qiwzhang** [comment]
If your header is not in the global dictionary,  it will be add as per-request dictionary in this field <https://github.com/istio/api/blob/master/mixer/v1/attributes.proto#L114>.  The index will be negative.  Please look at the comment of the top of "CompressedAttributes" on how to set the index.  
This is all part of compression scheme for CompressedAttributes.

**Comment by domwong** [comment]
Thanks @qiwzhang . I've managed to track down the issue as a bug in istio mixer which I'll fix and PR on that repo. Will close this.
