### ISSUE TITLE
Proposing myself as a collaborator

### ISSUE THREAD

**Issue by ymesika** [istio/proxy#1963]
Darwin builds for the proxy are currently hosted on some personal bucket and stuck in `0.7.1`: https://github.com/istio/istio/blob/master/bin/init.sh#L101

I don't mind building for MacOS with each release of proxy and adding the build for the released tag but I need to be a collaborator to be able to edit releases and add the binary.

Therefore I'm proposing myself as a collaborator only for this purpose.

**Comment by qiwzhang** [comment]
@ymesika    For release, most likely it is in istio/istio repo.   Could you move the issue there?

**Comment by ymesika** [comment]
@qiwzhang istio/istio is not the right place to host a proxy release. The binaries needs to be placed somewhere so the script there will be able to download it.

Alternatively, just add the following file to the `1.0.2` release of **this** repo if you have the permission to do so.

[istio-proxy-1.0.2-macos.tar.gz](https://github.com/istio/proxy/files/2367556/istio-proxy-1.0.2-macos.tar.gz)

**Comment by qiwzhang** [comment]
I see.  I don't have permission either.  @hklai may have

**Comment by hklai** [comment]
@ymesika do you mean adding to https://github.com/istio/proxy/releases/tag/1.0.2?

I suppose we should automate that in the release if that is important. Could you elaborate the use cases and how you build the mac binary?

**Comment by ymesika** [comment]
@hklai That's the place.

To automate it you will need a Mac to run the build on. Do you have such as part of the release process? Anyway, I checkout the desired tag of the repo and run the make build to create the envoy binary. I'm pretty sure I had to install some pre-requisites until I had the bazel build working but it was long time ago.

This is useful for people like myself who wish to run tests locally and it worked well until recent envoy added a new flag which fails the test on a Mac: https://github.com/istio/istio/issues/8299

**Comment by hklai** [comment]
@ymesika we currently don't run any mac build. In fact, we don't even build proxy in the release progress. Instead, wea rely on the regular proxy build from the post submit jobs. We have a plan to do better and perhaps we should incorporate mac build in it too.

In the mean time, I have updated https://github.com/istio/proxy/releases/tag/1.0.2 with the binary. PTAL

**Comment by ymesika** [comment]
Great. Thanks @hklai !

**Comment by PiotrSikora** [comment]
The `istio-proxy-1.0.2-macos.tar.gz` is wrong, it has `envoy` at the root of the package, whereas Linux packages have it under `usr/local/bin/envoy`, which breaks `make init` in `istio/istio`.

cc @nmittler @rkpagadala

**Comment by dunjut** [comment]
cc @hklai 

The `istio-proxy-1.0.2-macos.tar.gz` needs to be fixed of file path.

**Comment by hklai** [comment]
@ymesika could you fix it? I can then upload the file again.

**Comment by PiotrSikora** [comment]
Yeah, it seems that the previously uploaded `tar.gz` was created manually and not using Bazel... it was also `DEBUG` and not a `RELEASE` build.

I uploaded `tar.gz` produced using:
```
$ git checkout 1.0.2
$ bazel build --config=release-symbol //src/envoy:envoy_tar
```
it should be available at the same URL as the previous file.

```
$ shasum -a 256 istio-proxy-1.0.2-macos.tar.gz 
ef7dabb5f72122b625e219557b02c9405e8bbc1af95219b112e5f9c514d888b2  istio-proxy-1.0.2-macos.tar.gz
$ shasum -a 256 ./usr/local/bin/envoy 
4aa5188e6bafc8e30cc503250e487324e71f091a9bc98744d85e63bbb73e7ed6  ./usr/local/bin/envoy
```

**Comment by ymesika** [comment]
@PiotrSikora Thanks for correcting the tar.

I'm glad we finally have an updated envoy and also what's needed to create it in future releases.
