### ISSUE TITLE
Injecting a JWT obtained from an external endpoint during sidecar communication

### ISSUE THREAD

**Issue by mefarazath** [istio/proxy#1983]
I have two services deployed in an istio mesh and secured each with JWT authentication. 

Suppose if the two services need to talk to each other, Is there any extension point in the flow which I could use to inject a valid JWT into the request going from on service to other. I can obtain the JWT by calling an external service or endpoint.

**Comment by kyessenov** [comment]
Guide available here https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide
