### ISSUE TITLE
 Invalid inline jwks for issuer: testing@secure.istio.io, jwks: {"keys":[]}

### ISSUE THREAD

**Issue by zhaorendong** [istio/proxy#2072]
I created the policy like following:

apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example2"
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "http://192.168.18.3:8083/oauth/key"
  principalBinding: USE_ORIGIN

The policy worked well, but when the jwk invalid and my oauth server updated a new jwk, the sidecar (envoy)  didn't update the new jwk. Then I tried to create a new policy and renemed it "jwt-example3" like following:
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example3"
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "http://192.168.18.3:8083/oauth/key"
  principalBinding: USE_ORIGIN

The sidecar updated the new jwk. But sometimes, the sidecar logs : 
[2018-12-24 03:05:58.368][14][warning][filter] ./src/envoy/http/jwt_auth/pubkey_cache.h:84] Invalid inline jwks for issuer: testing@secure.istio.io, jwks: {"keys":[]}
[2018-12-24 03:05:58.369][19][warning][filter] ./src/envoy/http/jwt_auth/pubkey_cache.h:84] Invalid inline jwks for issuer: testing@secure.istio.io, jwks: {"keys":[]}
[2018-12-24 03:05:58.369][20][warning][filter] ./src/envoy/http/jwt_auth/pubkey_cache.h:84] Invalid inline jwks for issuer: testing@secure.istio.io, jwks: {"keys":[]}

So I want to know what causes it?

**Comment by qiwzhang** [comment]
Could you get config_dump from the Envoy admin port to see what config Pilot send to Envoy?  JWK is fetched by the Pilot.

**Comment by lei-tang** [comment]
The failing case using the URL https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com as the jwksUri is due that the key format in this URL is not supported by Istio Envoy proxy. Please refer to https://tools.ietf.org/html/rfc7517 for the format of the json web key.

- The jwks in the working config ("https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json") is of the following format, which is consistent with the json web key format in https://tools.ietf.org/html/rfc7517.
 "keys": [
    {
      "e": "AQAB",
      "kid": "DHFbpoIUqrY8t2zpA2qXfCmr5VO5ZEr4RzHU_-envvQ",
      "kty": "RSA",
      "n": "xAE...."
    }
  ]

- The key in the failing config ("https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com") is of the following format, which is not consistent with the json web key format in https://tools.ietf.org/html/rfc7517.
{
  "91fc60858e1c4133c82216d53dd179fa41f8430c": "-----BEGIN CERTIFICATE-----....-----END CERTIFICATE-----\n",
  "859a641a1b82cc3b50a801bf50640f38257d1299": "-----BEGIN CERTIFICATE-----... -----END CERTIFICATE-----\n"
}

**Comment by lei-tang** [comment]
This issue is closed as expected behavior: the format of the jwks acceptable for Istio proxy is defined by the standard https://tools.ietf.org/html/rfc7517; the key in the failing config ("https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com") is not of the jwks format in https://tools.ietf.org/html/rfc7517.

**Comment by jcurlier** [comment]
Thanks @lei-tang

**Comment by jcurlier** [comment]
I found the valid file for Firebase for the certificate:
```
issuer: "https://securetoken.google.com/aura-dev"
jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
```

**Comment by jcurlier** [comment]
The URL has an expiration of Fri, 25 Jan 2019 02:38:45 GMT - do you know if it will refresh the certificate?
