### ISSUE TITLE
How to make the JWK refresh envoy as soon as it is updated

### ISSUE THREAD

**Issue by zhaorendong** [istio/proxy#2119]
How to make the JWK refresh envoy as soon as it is updated. Is there anything you can configure? In other words， can the envoy get the new JWk at once when I create a new policy？

**Comment by yangminzhu** [comment]
Istio proxy doesn't fetch the public key, it gets it from Pilot. See more here: https://github.com/istio/istio/issues/10547.

I will close this one as it's not related to the istio/proxy repo. Thanks.
