### ISSUE TITLE
Istio Proxy logs are spammed with warnings about deprecation from Envoy

### ISSUE THREAD

**Issue by pitlv2109** [istio/proxy#2159]
Currently, Istio Proxy logs are filled with warnings about deprecation like:

> [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.route.Route.per_filter_config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details

These warnings take a large portion of the logs (e.g. 80-90% when debugging RBAC). 

**Expected behavior:**
Much less deprecation warings.

**Comment by esnible** [comment]
See https://github.com/istio/proxy/issues/2234#issuecomment-496966804

**Comment by howardjohn** [comment]
This is fixed in 1.2, see https://github.com/istio/proxy/issues/2234#issuecomment-496966804

As far as actually migrating off the deprecated features, I believe there is work being done in these areas. if not we should open issues for those, but the actual log issue has been solved
