### ISSUE TITLE
OPTION JWT authentication bypass not working

### ISSUE THREAD

**Issue by procyclinsur** [istio/proxy#2160]
**Issue**
---
I have cross-site traffic going from app.service.net going to api.service.net.  The application is required to authenticate this traffic with istio via JWT.  However during the initial interaction OPTIONS is being forced to authenticate with istio.  Since OPTIONS commands do not include `Authentication` headers it fails with `401 unauthorized`.

As I understand it, the below issues/PRs are supposed to have fixed this issue:
#651 
#2139 
#2140 

Is there anything I am missing from these issues that is preventing me from properly configuring the bypass for OPTIONS or has this become an issue again?

I have listed my configuration and versions below.

**Configuration**
---

**Istio/Kubernetes Version**

```
[procyclinsur@P-428 core-api]$ istioctl version
version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}

[procyclinsur@P-428 core-api]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**JWT Policy**

* namespace: istio-system

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: core-api-jwt-auth
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 443
  origins:
  - jwt:
      audiences:
      - 4i00tescmmXXXXXX6c1chlvhpq
      issuer: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX
      jwksUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX/.well-known/jwks.json
  principalBinding: USE_ORIGIN
```

**ingress-gateway:**

* namespace: istio-system

istio-ingressgateway is default aside from being an AWS NLB as opposed to an AWS CLB.

**gateway**

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: core-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.service.net"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "api.service.net"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**virtual service** 

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: core-api-virtual-service
spec:
  hosts:
  - "api.service.net"
  gateways:
  - core-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: core-api-service
        port:
          number: 80
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
      allowHeaders:
        - content-type
        - authorization
      maxAge: 300s
      allowCredentials: false

**Comment by procyclinsur** [comment]
@lei-tang I wanted to check with you as you originally created the fix for this issue.  It seems like the fix may not be working any longer??

**Comment by lei-tang** [comment]
Per the implementation at https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L71, for an OPTIONS request to be bypassed, the request must 1)be of OPTIONS method, 2)the origin must be non-empty, 3)AccessControlRequestMethod must be non-empty. Can you turn on the debug log and see if the requests meet the above conditions? If the requests do not meet these conditions, they will not be bypassed the JWT authentication as OPTIONS requests. Meanwhile, based on https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L82, when the requests are authenticated by JWT authenticator, the log message "Jwt authentication starts" should be printed. If such log message is not printed, the request is not going through the JWT authentication.

**Comment by procyclinsur** [comment]
@lei-tang Thank you for the response, I have turned debugging on and receive the following in my istio-ingressgateway logs.

```
{
	"bytes_sent": "29",
	"upstream_cluster": "-",
	"downstream_remote_address": "10.20.204.109:54546",
	"path": "/query",
	"authority": "api.service.net",
	"protocol": "HTTP/2",
	"upstream_service_time": "-",
	"upstream_local_address": "-",
	"duration": "0",
	"downstream_local_address": "10.20.28.35:443",
	"response_code": "401",
	"user_agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
	"response_flags": "-",
	"start_time": "2019-04-09T01:32:23.657Z",
	"method": "2019-04-09T01:32:23.657Z",
	"request_id": "5ed11fca-7745-4bed-8f80-b3759d121488",
	"upstream_host": "-",
	"x_forwarded_for": "10.20.204.109",
	"requested_server_name": "api.service.net",
	"bytes_received": "0",
	"istio_policy_status": "-"
}
```
This is very strange, as the headers specifically sent from the browser look like this..

![image](https://user-images.githubusercontent.com/34673206/55767596-82685700-5ab4-11e9-81f2-b27834bff45f.png)

do you have any idea what might be causing istios logs to show this descrepency, right now istio is outputing only traffic headers, I will search for more detailed logging as well.

**Comment by lei-tang** [comment]
Perhaps the logs in the post { "bytes_sent": "29" ....}  are not Istio Envoy proxy logs. The [link ](https://istio.io/help/ops/security/debugging-authorization/#ensure-proxies-enforce-policies-correctly) has an example of turning on the debug logging in Istio Envoy proxy.

**Comment by procyclinsur** [comment]
@lei-tang I tried turning on various debug logs, many of them gave no apparent clues, however when enabling debug on the `http` and `filter` logs the following appears.  

For HTTP debug logs, it seems that the request is coming in as expected.

```
[2019-04-09 02:43:34.032][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:548] [C3418170][S11505245908276168822] request headers complete (end_stream=true):
':method', 'OPTIONS'
':path', '/query'
':authority', 'api.service.net'
':scheme', 'https'
'user-agent', 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
'accept', '*/*'
'accept-language', 'en-US,en;q=0.5'
'accept-encoding', 'gzip, deflate, br'
'access-control-request-method', 'POST'
'access-control-request-headers', 'authorization,content-type'
'referer', 'http://localhost:8080/'
'origin', 'http://localhost:8080'
'cache-control', 'max-age=0, no-cache'
'pragma', 'no-cache'
'te', 'trailers'

[2019-04-09 02:43:34.032][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:990] [C3418170][S11505245908276168822] request end stream
[2019-04-09 02:43:34.032][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1225] [C3418170][S11505245908276168822] encoding headers via codec (end_stream=false):
':status', '401'
'content-length', '29'
'content-type', 'text/plain'
'date', 'Tue, 09 Apr 2019 02:43:33 GMT'
'server', 'istio-envoy'

{
	"bytes_sent": "29",
	"upstream_cluster": "-",
	"downstream_remote_address": "10.20.204.109:55520",
	"path": "/query",
	"authority": "api.service.net",
	"protocol": "HTTP/2",
	"upstream_service_time": "-",
	"upstream_local_address": "-",
	"duration": "0",
	"downstream_local_address": "10.20.28.35:443",
	"response_code": "401",
	"user_agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
	"response_flags": "-",
	"start_time": "2019-04-09T02:43:34.032Z",
	"method": "2019-04-09T02:43:34.032Z",
	"request_id": "674c2e4f-fcbf-43c4-beb2-327a081dcbe3",
	"upstream_host": "-",
	"x_forwarded_for": "10.20.204.109",
	"requested_server_name": "api.service.net",
	"bytes_received": "0",
	"istio_policy_status": "-"
}
```

The `filter` debug log also appears to show no apparent dependencies. 

```
[2019-04-09 03:05:23.865][35][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:73] tls inspector: new connection accepted
[2019-04-09 03:05:23.869][35][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:119] tls:onServerName(), requestedServerName: api.service.net
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/mixer/filter.cc:39] Called Mixer::Filter : Filter
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/mixer/filter.cc:146] Called Mixer::Filter : setDecoderFilterCallbacks
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/jwt_auth/jwt_authenticator.cc:62] Jwt authentication starts
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/jwt_auth/jwt_authenticator.cc:223] Jwt authentication completed with: OK
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/jwt_auth/jwt_authenticator.cc:226] The value of allow_missing_or_failed in AuthFilterConfig is: true
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/jwt_auth/http_filter.cc:55] JwtVerificationFilter::onDone with status OK
[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/authn/http_filter.cc:48] AuthenticationFilter::decodeHeaders with config
policy {
  origins {
    jwt {
      issuer: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_SsOilqOxs"
      audiences: "4i00tescmm5b2uco6c1chlvhpq"
      jwks_uri: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_SsOilqOxs/.well-known/jwks.json"
      }
    }
  }
  principal_binding: USE_ORIGIN
}
jwt_output_payload_locations {
  key: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_SsOilqOxs"
  value: "istio-sec-97159133387e0eeeb9e4cca917afa409f3212a3f"
}

[2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/authn/peer_authenticator.cc:36] No method defined. Skip source authentication.
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/authn/filter_context.cc:81] No dynamic_metadata found for filter jwt-auth
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/authn/origin_authenticator.cc:83] Origin authenticator failed
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/mixer/filter.cc:133] Called Mixer::Filter : encodeHeaders 0
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/authn/http_filter.cc:42] Called AuthenticationFilter : onDestroy
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/mixer/filter.cc:205] Called Mixer::Filter : onDestroy state: 0
[2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/mixer/filter.cc:219] Called Mixer::Filter : log
[2019-04-09 03:05:23.889][35][debug][filter] [./src/envoy/http/mixer/report_data.h:132] No dynamic_metadata found for filter envoy.filters.http.rbac
[2019-04-09 03:05:23.890][35][debug][filter] [src/istio/control/client_context_base.cc:125] Report attributes: attributes {
  key: "connection.mtls"
  value {
    bool_value: false
  }
}
attributes {
  key: "connection.requested_server_name"
  value {
    string_value: "api.service.net"
  }
}
attrib
[2019-04-09 03:05:24.192][34][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:73] tls inspector: new connection accepted
[2019-04-09 03:05:24.540][35][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:73] tls inspector: new connection accepted
{
	"upstream_host": "-",
	"x_forwarded_for": "10.20.204.109",
	"requested_server_name": "api.service.net",
	"bytes_received": "0",
	"istio_policy_status": "-",
	"bytes_sent": "29",
	"upstream_cluster": "-",
	"downstream_remote_address": "10.20.204.109:55776",
	"path": "/query",
	"authority": "api.service.net",
	"protocol": "HTTP/2",
	"upstream_service_time": "-",
	"upstream_local_address": "-",
	"duration": "1",
	"downstream_local_address": "10.20.28.35:443",
	"response_code": "401",
	"user_agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
	"response_flags": "-",
	"start_time": "2019-04-09T03:05:23.888Z",
	"method": "2019-04-09T03:05:23.888Z",
	"request_id": "43103995-d15d-4771-98bf-0ee81f56479d"
}
[2019-04-09 03:05:24.888][35][debug][filter] [./src/envoy/utils/header_update.h:46] Mixer forward attributes set: Ck8KCnNvdXJjZS51aWQSQRI/a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LTc5NGNmY2Y4YmMtY2twbTcuaXN0aW8tc3lzdGVt
```

I am continuing to look for clues in the debug log.  Please let me know if there is anything I am missing?

**Comment by lei-tang** [comment]
The following lines in the logs indicate that the request was going through JWT authentication.
- [2019-04-09 03:05:23.888][35][debug][filter] [src/envoy/http/jwt_auth/jwt_authenticator.cc:62] Jwt authentication starts
- [2019-04-09 03:05:23.889][35][debug][filter] [src/envoy/http/authn/origin_authenticator.cc:83] Origin authenticator failed

https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L71 bypasses the JWT authenticaion for a request if the request 1)be of OPTIONS method, 2)the origin must be non-empty, 3)AccessControlRequestMethod must be non-empty. As the logs show the request is going through JWT authentication, the request did not meet the above conditions. To figure out why the requests do not meet these conditions, you can add debugging statements in Verify() at https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L57.

**Comment by procyclinsur** [comment]
@lei-tang I was running through the procedures to rebuild istio with the required logging, and I was very surprised to find that your changes for JWT authentication do not exist in either the 1.1.1 or 1.1.2 tag or release!! I am 100% certain that this is why my OPTIONS method is not being bypassed..

As a release was pushed out just 8 days ago I am shocked to see it didn't include many of the outstanding commits to master.  

Is this the expected result? 
Should I rebuild from master instead?
Who do we need to talk to to get a new release with your contributions?

**Comment by lei-tang** [comment]
I created a PR https://github.com/istio/proxy/pull/2165 to cherry-pick the two PRs related to "Add the support of bypassing JWT authn for CORS requests" from master branch to release 1.1 branch. After the cherry-picked PR is merged, it should be included in the next Istio release. As to the time line for new releases, please reach out to @duderino.

**Comment by procyclinsur** [comment]
@lei-tang Thank you for the fast response! I am following #2165, and will adjust my installation as necessary until merged. 

@duderino When might I be able to expect this to be in a tagged release after merged?  Is there a timeframe for releases?

**Comment by cmacdonnacha** [comment]
Hey guys, just tried this in Istio 1.1.4 and I'm still seeing this issue where JWT authentication is being checked on an OPTIONS request.

**Comment by procyclinsur** [comment]
> Hey guys, just tried this in Istio 1.1.4 and I'm still seeing this issue where JWT authentication is being checked on an OPTIONS request.

@cmacdonnacha 

Yes, currently it seems it will be.. hopefully coming in v1.2 based on my conversations with the project owners.  However I have gotten no definitive answers on when that might be coming down the pipe...  That being said, as the 1.2 branch has not been cut from master yet, it seems to be a waiting game.

**Comment by Jonathan34** [comment]
So i am using gke which is using istio 1.0.6 and this appears to be working fine for me.
I have an auth policy set per namespace to validate jwt tokens. that policy is active for all services (so i define targets) except for the front end (which is used to authenticate the users and retrieve the jwt token)

This is the service definition (api-myapp.domain.com) that the ui (https://myapp-ui.domain.com) is calling:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-routes-myapp
spec:
  hosts:
    - api-myapp.domain.com
  gateways:
    - istio-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /api/v1/myapp
      route:
        - destination:
            host: myapp
            port:
              number: 3000
      corsPolicy:
        allowOrigin:
          - "https://myapp-ui.domain.com"
        allowMethods:
          - POST
          - GET
          - OPTIONS
        allowCredentials: false
        allowHeaders:
          - Authorization
          - Content-type
        maxAge: "24h"
    - match:
        - uri:
            prefix: /somePath
      route:
        - destination:
            host: myapp
            port:
              number: 3001
```
hopefully it is helpful for someone.

**Comment by procyclinsur** [comment]
> > Hey guys, just tried this in Istio 1.1.4 and I'm still seeing this issue where JWT authentication is being checked on an OPTIONS request.
> 
> @cmacdonnacha
> 
> Yes, currently it seems it will be.. hopefully coming in v1.2 based on my conversations with the project owners. However I have gotten no definitive answers on when that might be coming down the pipe... That being said, as the 1.2 branch has not been cut from master yet, it seems to be a waiting game.

From the Istio Slack!

Q: Do we have a target of when to release 1.2 yet?
A: freeze in may 21st release in june 22

**Comment by duderino** [comment]
This will be in both 1.1.9 (est release date 6/17/19) and 1.2.0 (est release date 6/18/19)

**Comment by procyclinsur** [comment]
@duderino Thank you!! I will test this out and then close this today or tomorrow (JST)

**Comment by procyclinsur** [comment]
tested release 1.2.. closing

**Comment by lei-tang** [comment]
@procyclinsur Thank you for confirming that the solution works on release 1.2!
