### ISSUE TITLE
Allow fail-open and fail-closed calls in mixerfilter

### ISSUE THREAD

**Issue by kyessenov** [istio/proxy#263]
Currently, failure to send calls to Mixer causes the proxy to deny all requests. We need to make this behavior configurable and allow fail-open option globally or per service.

@louiscryan @ZackButcher @qiwzhang

**Comment by qiwzhang** [comment]
We can do a global one first.    How about adding this flag in mixer filter config

network_fail_policy: open or close.

Default is open.

**Comment by kyessenov** [comment]
Sounds reasonable. We may need fail-close for stronger authz but that is for later.

**Comment by qiwzhang** [comment]
Do we need this for alpha? Or this can wait?

**Comment by kyessenov** [comment]
Make it default fail-open for alpha?
