### ISSUE TITLE
Traffic should be treated as in-cluster after being accepted by the Ingress.

### ISSUE THREAD

**Issue by andraxylia** [istio/proxy#281]
Traffic should be treated as in-cluster after being accepted by the Ingress.
Ingress-proxy should talk with mixer.

**Comment by qiwzhang** [comment]
@mandarjog or @kyessenov could you help me to understand the issue?  It seems that we have terminology gaps.

**Comment by kyessenov** [comment]
This is about ingress proxy not setting source mixer attributes. I think the issue is in the wrong place.

**Comment by andraxylia** [comment]
I opened this in proxy repository in case there are changes required in the mixer filter to support this functionality. If you are positive there are no changes needed, feel free to close it.
