### ISSUE TITLE
Proxy segfault

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#286]
Happened after testing with ~1000 requests for a long time.

Stack trace on envoy:

(gdb) bt
#0 0x0000000003357c08 in ?? ()
#1 0x0000000000448acf in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&) ()
#2 0x0000000000526946 in Event::DispatcherImpl::runPostCallbacks() ()
#3 0x000000000078ef81 in event_process_active_single_queue (base=base@entry=0x308e2c0, activeq=0x2efc210, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1646
#4 0x000000000078f887 in event_process_active (base=0x308e2c0) at event.c:1738
#5 event_base_loop (base=0x308e2c0, flags=0) at event.c:1961
#6 0x00000000005213d1 in Worker::threadRoutine(Server::GuardDog&) ()
#7 0x00000000005c797e in Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) ()
#8 0x00007f3a7aec766a in __reclaim_stacks () at allocatestack.c:946
#9 0xa7db176b218c89d7 in ?? ()
#10 0x0000000000000000 in ?? ()

**Comment by qiwzhang** [comment]
copied from https://github.com/istio/manager/issues/656

**Comment by mandarjog** [comment]
Hit another
docker.io/istio/proxy:2017-05-01-19.24.52


```
#0  0x0000000000000000 in ?? ()
#1  0x00000000005a2ade in Http::ConnectionManagerImpl::ActiveStreamFilterBase::commonContinue() ()
#2  0x0000000000448acf in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&) ()
#3  0x0000000000526946 in Event::DispatcherImpl::runPostCallbacks() ()
#4  0x000000000078ef81 in event_process_active_single_queue (base=base@entry=0x1fe42c0, activeq=0x1e56220, 
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1646
#5  0x000000000078f887 in event_process_active (base=0x1fe42c0) at event.c:1738
#6  event_base_loop (base=0x1fe42c0, flags=0) at event.c:1961
#7  0x00000000005213d1 in Worker::threadRoutine(Server::GuardDog&) ()
#8  0x00000000005c797e in Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) ()
#9  0x00007effc93d666a in queue_stack (stack=0x7c0270) at allocatestack.c:310
#10 __deallocate_stack (pd=0x7c0270) at allocatestack.c:774
```

**Comment by mandarjog** [comment]
@costinm @qiwzhang I hit this several times.

**Comment by qiwzhang** [comment]
With the latest proxy? or at least the proxy with last crash fix?

**Comment by mandarjog** [comment]
good, point. It does not have that fix, but the line number looks different.

https://github.com/istio/istio/pull/198

Sent in an update PR.

**Comment by qiwzhang** [comment]
Cool,  I have been looking at that code for over a hour. Could not explain it.  Now it made sense.
