### ISSUE TITLE
Support HTTP_PROXY / HTTPS_PROXY as alternate means of proxying

### ISSUE THREAD

**Issue by mandarjog** [istio/proxy#299]
For Cloud Foundry and a few other applications, using HTTP*_PROXY variables is the best way to inject proxy. 
For HTTP_PROXY it looks like our proxy will simply work. it will be a snap in replacement for the iptables magic.  

For HTTPS_PROXY, envoy needs to support  `http CONNECT` method.

**Comment by mandarjog** [comment]
@rshriram @louiscryan

**Comment by ldemailly** [comment]
side note: https proxying (connect) isn't really like a proxy as you won't have access to anything about the request, it's basically like a socket after connect - we'd have to terminate ssl at the proxy I think

**Comment by kyessenov** [comment]
I'm not familiar with Cloud Foundry, but that's an important concern. We might require usage of HTTP_PROXY to get features of Istio.

**Comment by ldemailly** [comment]
I think we do have some support for this actually ?

**Comment by kyessenov** [comment]
It's just wrong repo. Yes, there's some issue in pilot about this.

**Comment by ldemailly** [comment]
k follow up in https://github.com/istio/pilot/issues/1129
