### ISSUE TITLE
istio/proxy image doesn't contain transcoding filter ?

### ISSUE THREAD

**Issue by jwfang** [istio/proxy#307]
using 0.1.1 istio/proxy from docker hub

got the following error:
> [2017-05-12 09:40:57.195][31][critical][main] error initializing configuration 'envoy-t.conf': unable to create http filter factory for 'transcoding'/'both'

and there's no transcoding related symbols in envoy:
```bash
nm envoy | fgrep -c TranscodingConfig
0
nm envoy | fgrep -c MixerConfig
68
```

**Comment by qiwzhang** [comment]
You may have looked at wrong file.  I just unpacked docker.io/istio/proxy:0.1.1

nm envoy |grep MixerConfig
0000000000413be0 t _GLOBAL__sub_I__ZN4Http5Mixer11HttpControlC2ERKNS0_11MixerConfigE
0000000000413aa0 t _GLOBAL__sub_I__ZN4Http5Mixer11MixerConfig4LoadERKN4Json6ObjectE
000000000095cde0 u _ZGVZN6Server13Configuration31RegisterHttpFilterConfigFactoryINS0_11MixerConfigEEC4EvE8i

**Comment by jwfang** [comment]
i have mixer filter, but want to test grpc *transcoding* filter

**Comment by kyessenov** [comment]
Hey, transcoding filter is not complete. @lizan is driving the implementation. You might have been confused by presence of the code in `contrib/` but it hasn't been fully integrated into envoy.

**Comment by jwfang** [comment]
tnanks.

looking forward for its launch.

istio project looks really promising.

**Comment by qiwzhang** [comment]
I see the problem now.  The envoy binary build from //src/envoy/mixer doesn't have transcoding feature
Only the envoy binary build from //src/envoy/transcoding has.  istio/proxy only use the one from //src/envoy/mixer

**Comment by jwfang** [comment]
what's the status for transcoding filter from istio/proxy ?
i mean at least for development testing.

 do you plan to including both filters in istio/proxy docker images ?  i am a bazel virgin, or else i could help do it.

i see some discussion on github to integrate the transcoding filter into core envoy,  should i wait till then to test-drive the transcoding feature ?

**Comment by kyessenov** [comment]
The plan is to make transcoding part of core Envoy so that's the same plan. Istio proxy will just have mixer filter on top of base envoy. The current code is functional and works for nginx.

**Comment by qiwzhang** [comment]
If you want to try it now,  you just build an envoy binary from //src/envoy/transcoding:envoy.

**Comment by lizan** [comment]
@jwfang You can build `//src/envoy/transcoding:envoy` to test transcoding filter, or define a target contains both filter. transcoding support is still under development and not fully tested.

cc lyft/envoy#501

**Comment by jwfang** [comment]
thank you guys
