### ISSUE TITLE
can't build using bazle

### ISSUE THREAD

**Issue by jwfang** [istio/proxy#308]
git_repository(
    name = "envoy",
    remote = "https://github.com/lyft/envoy.git",
    commit = "54d724bcfdd0de27ca5ae9238b258b37a28c978b",
)

for 54d724bcfdd0de27ca5ae9238b258b37a28c978b, 

from bazel/repository.sh
>  30 set -o pipefail
>  31 BUILD_LOG="${BASEDIR}"/build.log
>  32 (time ./build_and_install_deps.sh ${DEPS}) 2>&1 | tee "${BUILD_LOG}"
>  33

build_and_install_deps.sh seems to be in ci directory

**Comment by qiwzhang** [comment]
There are some special requirements to build Envoy, such as need gcc-4.9 and bazel 4.5
You can try to build git clone envoy and make sure it build first. 

If you

**Comment by jwfang** [comment]
when building fron HEAD, i got
> time: command not found

and traced down that *build_and_install_deps.sh* not in *bazel* directory but in *ci* directory.

**Comment by kyessenov** [comment]
Current bazel build in envoy is not hermetic, it requires some unix tools like time to be installed. Please see a list of dependencies here: https://github.com/istio/test-infra/blob/master/scripts/linux-install-software#L23

**Comment by jwfang** [comment]
kyessenov, you're really helpful.

btw, how do you build manager/mixer/proxy and the related containers in all?
using istio/test-infra you just mentioned?

**Comment by kyessenov** [comment]
I think individual repos have scripts to build docker images. in manager it's in `bin/e2e.sh` and those images include the proxy binary. No need to struggle with running Jenkinsfiles locally.

**Comment by jwfang** [comment]
thanks.
i think i have to do some greping. :)
