### ISSUE TITLE
Crash with mixer enabled

### ISSUE THREAD

**Issue by costinm** [istio/proxy#316]
Simple test with 'wrk  -c 100 -t 100 -d 30s'

Stack trace (in gdb):

#0  0x0000000000000000 in ?? ()
#1  0x000000000043ff67 in Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>) ()
#2  0x000000000044088f in Http::Mixer::Instance::callQuota(google::protobuf::util::Status const&) ()
#3  0x0000000000440012 in Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const ()
#4  0x0000000000442cc0 in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&)
    ()
#5  0x0000000000429c29 in std::function<void (google::protobuf::util::Status const&)>::operator()(google::protobuf::util::Status const&) const ()
#6  0x000000000043fe0d in Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}::operator()() const ()
#7  0x000000000044266b in std::_Function_handler<void (), Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#8  0x00000000004665fe in std::function<void ()>::operator()() const ()
#9  0x000000000062915e in Event::DispatcherImpl::runPostCallbacks() ()
#10 0x0000000000628525 in Event::DispatcherImpl::DispatcherImpl()::{lambda()#2}::operator()() const ()
#11 0x00000000006294ac in std::_Function_handler<void (), Event::DispatcherImpl::DispatcherImpl()::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#12 0x00000000004665fe in std::function<void ()>::operator()() const ()
#13 0x0000000000630cb5 in Event::TimerImpl::TimerImpl(Event::DispatcherImpl&, std::function<void ()>)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const ()
#14 0x0000000000630ce4 in Event::TimerImpl::TimerImpl(Event::DispatcherImpl&, std::function<void ()>)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) ()
#15 0x0000000000b32638 in event_process_active_single_queue.isra ()
#16 0x0000000000b32b9f in event_base_loop ()
#17 0x00000000006290bc in Event::DispatcherImpl::run(Event::Dispatcher::RunType) ()
#18 0x0000000000612e68 in Worker::threadRoutine(Server::GuardDog&) ()
#19 0x000000000061287e in Worker::initializeConfiguration(Server::Configuration::Main&, std::map<Server::Configuration::Listener*, std::unique_ptr<Network::TcpListenSocket, std::default_delete<Network::TcpListenSocket> >, std::less<Server::Configuration::Listener*>, std::allocator<std::pair<Server::Configuration::Listener* const, std::unique_ptr<Network::TcpListenSocket, std::default_delete<Network::TcpListenSocket> > > > > const&, Server::GuardDog&)::{lambda()#2}::operator()() const ()
#20 0x000000000061324f in std::_Function_handler<void (), Worker::initializeConfiguration(Server::Configuration::Main&, std::map<Server::Configuration::Listener*, std::unique_ptr<Network::TcpListenSocket, std::default_delete<Network::TcpListenSocket> >, std::less<Server::Configuration::Listener*>, std::allocator<std::pair<Server::Configuration::Listener* const, std::unique_ptr<Network::TcpListenSocket, std::default_delete<Network::TcpListenSocket> > > > > const&, Server::GuardDog&)::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#21 0x00000000004665fe in std::function<void ()>::operator()() const ()
#22 0x0000000000801304 in Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::operator()(void*) const ()
#23 0x0000000000801329 in Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) ()
#24 0x00007ffff79b96ba in start_thread (arg=0x7ffff02d9700) at pthread_create.c:333
#25 0x00007ffff6e4e82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by costinm** [comment]
Tried a new build at efa886a48a812c534fcad415c1faeaea265d16ec (before envoy rebase), different SIGSEGV:

#0  0x000000000043f9b5 in Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>) ()
#1  0x000000000044030f in Http::Mixer::Instance::callQuota(google::protobuf::util::Status const&) ()
#2  0x000000000043fa92 in Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const ()
#3  0x0000000000442740 in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&)
    ()
#4  0x00000000004296a9 in std::function<void (google::protobuf::util::Status const&)>::operator()(google::protobuf::util::Status const&) const ()
#5  0x000000000043f88d in Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}::operator()() const ()
#6  0x00000000004420eb in std::_Function_handler<void (), Http::Mixer::Instance::GetThreadJumpFunc(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#7  0x000000000046607e in std::function<void ()>::operator()() const ()
#8  0x0000000000605aa4 in Event::DispatcherImpl::runPostCallbacks() ()
#9  0x0000000000604e6b in Event::DispatcherImpl::DispatcherImpl()::{lambda()#2}::operator()() const ()
#10 0x0000000000605df2 in std::_Function_handler<void (), Event::DispatcherImpl::DispatcherImpl()::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#11 0x000000000046607e in std::function<void ()>::operator()() const ()
#12 0x000000000060d5fb in Event::TimerImpl::TimerImpl(Event::DispatcherImpl&, std::function<void ()>)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const ()
#13 0x000000000060d62a in Event::TimerImpl::TimerImpl(Event::DispatcherImpl&, std::function<void ()>)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) ()
#14 0x0000000000af5e28 in event_process_active_single_queue.isra ()
#15 0x0000000000af638f in event_base_loop ()

**Comment by kyessenov** [comment]
seems to be related to thread jumping in streaming grpc. is this worth fixing or just document as a limitation and wait until the switch to unary?
