### ISSUE TITLE
Allow HTTP headers for check_cache_keys

### ISSUE THREAD

**Issue by gbrail** [istio/proxy#325]
The proxy config has a "check_cache_keys" attribute that determines which aspects of the request key to items in the "check cache." A common scenario will be a key that is used for authorization, such as the HTTP "Authorization" header. (Sometimes people use a query parameter for this purpose too, although it's not a good practice.)

In this case, we'd need to specify this header in the "check_cache_keys" part of the mixer filter config.

The syntax for this in the mixer itself is, for instance:
  request.headers["Authorization"]

I wasn't able to figure out how to put this in envoy.conf with all the brackets and quotes. Perhaps there's a syntax for this -- otherwise I think that we should find a way to support it.

(In fact, come to think of it, without this then if the mixer is being used for authentication, then the whole check_cache mechanism has to be turned off.)

**Comment by qiwzhang** [comment]
It is supported.  Please look at the file: https://github.com/istio/proxy/tree/master/src/envoy/mixer

The syntax will be:

"check_cache_keys": [
              "request.host",
              "request.path",
              "source.labels",
              "request.headers/Authorization",
         ]

**Comment by gbrail** [comment]
That did it. Thanks!
