### ISSUE TITLE
Rollout new version of Envoy container.

### ISSUE THREAD

**Issue by tommyulfsparre** [istio/proxy#385]
Hi! 

Its great that we can inject an Envoy container into an application pod, even better if it could be done automatically with PodPreset.  

If you have a large mesh, with different services, owned by different people I can see how upgrading Envoy might become problematic. Forcing everybody to redeploy their services to upgrade Envoy, might not fly. 

How does the story look for upgrading the running Envoy containers? Is this something istio will tackle?

**Comment by qiwzhang** [comment]
@kyessenov @ayj any comment?

Our plan is to use dynamic admission control to inject Envoy container.  I am not sure if PodReset allow injecting container.  If so, it may be simpler than using dynamic admission control.

**Comment by ayj** [comment]
Auto-injection via PodPreset is tracked with https://github.com/istio/pilot/issues/335 and more detailed design is documented [here](https://docs.google.com/document/d/1-5rLhv6MbB27lL8l2CWD6kR-eMa13_PPwOScVVZq8bo/edit).

Pods are relatively ephemeral so sidecar's could be explicitly upgraded by user using native k8s rolling-updates (or equivalents).

**Comment by qiwzhang** [comment]
Thanks @ayj  I will close this issue.

**Comment by tommyulfsparre** [comment]
@ayj @qiwzhang thx for the update, this was more related to the upgrade story than the PodPreset one.

I feel like it might be a tall order to force each service owner/user to manage their proxies and it would also be hard to push out new versions of Envoy. Some might never be upgraded. Pods being ephemeral doesn't change the version of Envoy in said pod unless the user doesn't bump it.

This could be solved outside of istio of course, was just curious to see if this was something the project had thought about.

**Comment by kyessenov** [comment]
We don't have a proposal for in-place update of Envoy binaries inside the container.
Envoy's management APIs should more or less stabilize in the coming months, when doing something like this can potentially work.

**Comment by ayj** [comment]
Fully transparent sidecar upgrades w/o restarting user pods would require in-place binary updates. A more explicit upgrade could be triggered by user (or on user's behalf) through existing k8s mechanisms which takes advantage of the fact that pods of ephemeral. As @kyessenov said, we don't have any proposal for either scheme at this time.
