### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by ldemailly** [istio/proxy#394]
envoy is now buildable on macOS but when I build I get
```
$ bazel build -c opt src/envoy/mixer:envoy
[...]
WARNING: /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy/bazel/repositories.bzl:31:5: External dep build exited with return code: 2.
WARNING: /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy/bazel/repositories.bzl:32:5: grep: /proc/cpuinfo: No such file or directory
.
WARNING: /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy/bazel/repositories.bzl:33:5: /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy_deps/./repositories.sh: line 9: md5sum: command not found

External dependency cache directory /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy_deps_cache_
.
ERROR: /private/var/tmp/_bazel_dl/eb119874c7b30dcafcbb687c93e2d621/external/envoy/bazel/repositories.bzl:178:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:spdlog'.
ERROR: Analysis of target '//src/envoy/mixer:envoy' failed; build aborted.
```

**Comment by lizan** [comment]
we haven't rebased to latest envoy contains the build fix.

**Comment by ldemailly** [comment]
it's close but still not there (for me, am I missing something ?)
```
ERROR: /private/var/tmp/_bazel_ldemailly/0811656893d1e79d77d5501da4894649/external/envoy/source/common/network/BUILD:11:1: C++ compilation of rule '@envoy//source/common/network:address_lib' failed (Exit 1).
external/envoy/source/common/network/address_impl.cc:81:15: error: use of undeclared identifier 'SOCK_NONBLOCK'
  int flags = SOCK_NONBLOCK;
              ^
1 error generated.
Target //src/envoy/mixer:envoy failed to build
```

**Comment by ldemailly** [comment]
the current (master) error seems not mac specific:

ERROR: /Users/ldemailly/go/src/istio.io/proxy/src/envoy/mixer/BUILD:44:1: C++ compilation of rule '//src/envoy/mixer:filter_lib' failed (Exit 1).
src/envoy/mixer/tcp_filter.cc:193:26: error: 'createFilterFactory' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  NetworkFilterFactoryCb createFilterFactory(const Json::Object& config,
                         ^
bazel-out/darwin_x86_64-opt/bin/external/envoy/include/envoy/server/_virtual_includes/filter_config_interface/envoy/server/filter_config.h:156:34: note: overridden virtual function is here
  virtual NetworkFilterFactoryCb createFilterFactory(const Json::Object& config,
                                 ^

**Comment by ldemailly** [comment]
works now except linking, how do I get uuid-dev equivalent on mac os ?

**Comment by lizan** [comment]
what is the error you're seeing? mac os has uuid by default so it shouldn't fail

**Comment by ldemailly** [comment]
```
ERROR: /Users/ldemailly/go/src/istio.io/proxy/src/envoy/mixer/BUILD:70:1: Linking of rule '//src/envoy/mixer:envoy' failed (Exit 1).
ld: library not found for -luuid
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Target //src/envoy/mixer:envoy failed to build
```

**Comment by lizan** [comment]
Hmm, short term solution:
comment out https://github.com/istio/proxy/blob/master/src/envoy/mixer/BUILD#L63 then it should build. (this break Linux build so don't make a PR)

Long term, https://github.com/istio/mixerclient/pull/94

**Comment by ldemailly** [comment]
thx ! there should be some magic way to tell bazel to use system's uuid when present
(and/or make a rule with an if for os x - but I don't know bazel at all so no idea)

**Comment by lizan** [comment]
Yes, we can conditionally link it using `select`, but once istio/mixerclient#94 is done there is no longer need of that, so I'd rather wait on that.
