### ISSUE TITLE
Populate {target, source}.{ip, port} on the HTTP path

### ISSUE THREAD

**Issue by ZackButcher** [istio/proxy#406]
Today we populate target.{source, ip} on the Report path for TCP:
https://github.com/istio/proxy/blob/6acef3806fa52cfe6cf2c2a2d37176320a7db460/src/envoy/mixer/mixer_control.cc#L355-L363

and source.{source, ip} on the Check path for TCP:
https://github.com/istio/proxy/blob/6acef3806fa52cfe6cf2c2a2d37176320a7db460/src/envoy/mixer/mixer_control.cc#L319-L324

We should be populating those attributes on HTTP traffic too, and if we have the information in hand we should be populating it on both Check and Report paths.

**Comment by qiwzhang** [comment]
It is not easy to get target.ip and port.  At HTTP OnHeader() calls,  upstream connection is not created yet.

Here is the PR to get source.ip and port.

https://github.com/istio/proxy/pull/408
