### ISSUE TITLE
Treat Mixer internal error same way as network failure

### ISSUE THREAD

**Issue by kyessenov** [istio/proxy#409]
Currently, an internal mixer errors (specifically, misconfiguration) results in total negative checks. I think we should treat any Mixer internal error the same way as a network error, that is it should be controlled by the same fail open/close parameter. Mixer filter should fail open if the setting is to fail open for any negative check due to an internal mixer error.

Follow up from the email cc @geeknoid @douglas-reid

**Comment by qiwzhang** [comment]
https://github.com/istio/mixerclient/pull/96

**Comment by mandarjog** [comment]
Moving the work to pilot https://github.com/istio/pilot/issues/1053.

**Comment by kyessenov** [comment]
before closing, I'd hope for some tests at last. it's already very hard to debug error scenarios.
