### ISSUE TITLE
Latest Envoy provides more useful server span tracing data

### ISSUE THREAD

**Issue by objectiser** [istio/proxy#413]
The current version of Envoy used in the engineering release of 0.2 only provides the `span.kind` tag for server spans. This has been changed in the last 5 days (haven't investigated the exact change or release) so that now the server spans also include all the relevant tags as in the client spans.

The previous approach is fine when a shared span model is being used (as in zipkin) but other tracing backends don't use the same approach - and therefore having more complete information in both the client and servers spans is beneficial. We currently have the zipkin data being consumed by Jaeger, but the server spans aren't very informative apart from their position in the trace.

Would it be possible to update to the latest Envoy version before releasing Istio 0.2?

**Comment by objectiser** [comment]
Here are some example images showing the issue. The first shows the trace with the individual client and server spans:

![istio-trace1](https://user-images.githubusercontent.com/164562/29366596-5d7833c6-8292-11e7-8f56-19720936736f.png)

The following shows an expanded server span, with just the 'span.kind = server' tag, and the following client span which shows many more tags.

![istio-trace2](https://user-images.githubusercontent.com/164562/29366604-61c20402-8292-11e7-9dc4-39f516bd06a4.png)

**Comment by qiwzhang** [comment]
https://github.com/istio/proxy/pull/414

should fix this.
