### ISSUE TITLE
cleanup proxy_debug image

### ISSUE THREAD

**Issue by ldemailly** [istio/proxy#423]
debug is good, kitchen sink is bad
now that we have `sudo apt-get install` working we don't need to install everyone's random editor and other huge footprint packages

**Comment by costinm** [comment]
busybox is pretty low footprint, it's designed from embedded systems - we
can remove emacs and several other packages in separate PR
if footprint is the concern.


On Tue, Aug 22, 2017 at 10:49 AM, Laurent Demailly <notifications@github.com

**Comment by ldemailly** [comment]
yes I meant for the other - though busybox itself is supposed to replace a full distro
we can use fortio instead of wrk etc
