### ISSUE TITLE
Add support for L4 network filters to the mixer client

### ISSUE THREAD

**Issue by kyessenov** [istio/proxy#44]
Currently, API manager operates at L7 (http*, grpc). We want L4 visibility into traffic for the mixer. This requires adding a network filter in Envoy and connecting it to the mixer client or extending the existing Envoy stats/tracing framework. Please check whether the provided L4 and L7 filters can operate on the same listener.

**Comment by ayj** [comment]
This should be doable in Envoy. Network filters can be chained together and the http_connection_manager is one type of network filter that dispatches out to any registered HTTP filters. 

See [here](https://github.com/lyft/envoy/blob/master/test/config/integration/server.json) for example envoy configuration with L4 (ratelimit) and L7 filters operating on the same listener.

**Comment by kyessenov** [comment]
@ayj Yes, we will to insert two filters at L4 and L7 for mixer client. I want to make sure that they can cooperate (e.g. do we send one "check" and "quota" call or two?)

**Comment by ayj** [comment]
Ideally, how do we want "check" and "quota" to behave with L4 and L7? My guess is that we'd want L4-level check/quota to apply for the initial L4 connection and then L7-level check/quota to apply once L7 traffic flows in addition to applying L4 quota. 

From envoy perspective this might work if the mixer client's L7 filter appears in the config before the L4 filter. If the L7 filter stops filter processing on match, the L4 filter would be skipped for L7 traffic and avoid double check/quota calls. The mixer client would then need to coordinate quota limits between its L4 and L7 filters, e.g. L7 filter updates L7 and L4 quota. 

@qiwzhang, @lizan  - do you think this would work?

**Comment by qiwzhang** [comment]
@ayj From L4 and L7 filters, if we can extract some sort of request_id to identify it is the same request, then mixer client can add some logic when calling Check and Quota.

**Comment by kyessenov** [comment]
L4 operates at connection level, so I'm not sure you can extract request there. L4 and L7 are sequenced as two independent filters in Envoy.

**Comment by qiwzhang** [comment]
One L4 connection may have many L7 requests (e.g. HTTP2).  For Check() and Quota,  most likely L4 and L7 should have different policy and should be done  independently. 

If we want to associate a L7 request to a L4, we could use tcp tuple (src ip/port, dst ip/port).

**Comment by lizan** [comment]
It should be possible to:
- generate an unique id for each L4 connection (might already exist in envoy)
- add that as an attribute in L7 filter 

Getting L4 connection info from L7 filter might need some changes in Envoy, but it is feasible

**Comment by kyessenov** [comment]
Is this really for alpha?
