### ISSUE TITLE
building envoy complains about protobuf_bzl

### ISSUE THREAD

**Issue by nimakaviani** [istio/proxy#445]
I am trying to build envoy proxy by running the following command as you have instructed in your docs:
```
bazel build //src/envoy/mixer:envoy
```
However the build fails with the follow error message:
```
ERROR: error loading package 'src/envoy/mixer': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed.
```

From what I have found on the web, the failure is either because of using older versions of bazel or because there is some missing submodule etc. In this case neither seems to be the case.

I am trying to build envoy on Mac with the following build tools:
```
$ bazel version
Build label: 0.5.4-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 16:52:09 2017 (1503679929)
Build timestamp: 1503679929
Build timestamp as int: 1503679929
$ protoc --version
libprotoc 3.4.0
```

Help is much appreciated.

**Comment by lizan** [comment]
@nimakaviani can you paste the full output of bazel? The ERROR complains about `protobuf_bzl` is usually caused by lack of build dependencies which listed [here](https://github.com/lyft/envoy/tree/master/bazel#quick-start-bazel-build-for-developers)

**Comment by ramaraochavali** [comment]
I am also running in to the same issue but in Ubuntu. I have all the dependencies. 
@nimakaviani were you able to solve this issue? If yes, can you please share the solution?

**Comment by nimakaviani** [comment]
sorry for the delayed reply. I got passed the initial problem but then got stuck at another place and got distracted by some other issues. In order to solve the protobuf issue, I had to add the following to the `WORKSPACE` file:

```
git_repository(
     name = "protobuf_bzl",
     remote = "https://github.com/htuch/protobuf.git",
     commit = "373809e5f5c1aa77b58c369b0d161ced93a04a4d",
)
```

then doing `bazel build ...:all` will get protobuf stuff into the external library. but then I got stuck at a new place where it was complaining about the `@envoy_deps` library:

```
make[1]: *** [low_level_alloc_unittest] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: link: c++ -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -ggdb3 -fno-omit-frame-pointer -O2 -Wl,-U -Wl,___lsan_ignore_object -o atomicops_unittest src/tests/atomicops_unittest.o -Wl,-bind_at_load  ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a -lpthread

real    1m8.760s
user    1m17.263s
sys     0m21.180s
make: *** [/private/var/tmp/_bazel_nimakaviani/1ba51d6d62c769331c6c891424d66c37/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep] Error 1
.
ERROR: /private/var/tmp/_bazel_nimakaviani/1ba51d6d62c769331c6c891424d66c37/external/envoy/bazel/repositories.bzl:202:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'.
ERROR: Analysis of target '//src/envoy/mixer:envoy' failed; build aborted.
````

**Comment by ramaraochavali** [comment]
@nimakaviani I was able to build it successfully. Couple of this I had to do is to set the GO related env vars correctly and point the TMPDIR to ~/tmp. If you still run in to issues, please share the command.log that is generated in ~/.cache/bazel/_bazel_<uname>/uniquenumber/command.log. I can see if I can help

**Comment by lizan** [comment]
@nimakaviani Adding that wouldn't help at all, please paste your full output of bazel.

**Comment by nimakaviani** [comment]
The output is pretty exhaustive so I tried to minimize it. Here is the full gist: https://gist.github.com/nimakaviani/978b39761bd1e39810bc6ac13e479309

**Comment by nimakaviani** [comment]
fyi, built it on xenial successfully.

The OSx issue seemd to be with the version of clang linker and the fact that it was not able to resolve symbols: `symbol(s) not found for architecture x86_64 `

It might be that the XCode clib linker is outdated, even though I used brew to upgrade the linker and that did not fix the issue.

**Comment by lizan** [comment]
What is your Xcode version? Envoy requires > 8.3.3

**Comment by lizan** [comment]
Also, we don't have official support for building on Mac and it is best effort, we have no CI for that.

**Comment by nimakaviani** [comment]
yes that's the problem. I think I am on an older version of XCode `7.3.1`. Closing the issue and thanks for the help
