### ISSUE TITLE
jwt-auth: updating public key regularly

### ISSUE THREAD

**Issue by mtakigiku** [istio/proxy#468]
- to implement the feature to fetch and update public key regularly
- to handle the case that second request comes before fetching public key completed

These two would be resolved simultaneously.

**Comment by nixgadget** [comment]
Any ETA on this ?

**Comment by qiwzhang** [comment]
I am working on this now.  ETA is a couple weeks.

**Comment by qiwzhang** [comment]
Will be tracked by https://github.com/istio/proxy/issues/720
