### ISSUE TITLE
Allow Pilot to pass any type of mesh attributes to Mixer

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#483]
Pilot generates Mesh attributes in Envoy Mixer filter config and Route Opaque data.  Now it only supports string type.   Other attribute types should be supported, such as BYTES for IP,  int for port.

Please see https://github.com/istio/mixerclient/issues/112

**Comment by douglas-reid** [comment]
@qiwzhang is there any way we can fix just the `destination.ip` attribute to use BYTES for 0.2.x?

cc: @geeknoid 

having `source.ip` sent as BYTES and `destination.ip` sent as STRING while both being IP_ADDRESS is not good. It makes writing config that refers to IP_ADDRESS attributes a near-impossibility and/or incredibly ugly (example: `match: destination.ip == "10.1.1.9" && source.ip == ip("10.10.10.1")`. It could also lead to some surprising results in metrics, depending on serialization etc.

**Comment by qiwzhang** [comment]
For 0.2, it has to be a hack:  any attribute names from Pilot with suffix as ".ip",  proxy needs to convert to bytes.   Then, we need similar hack for "port" which should be integer, but now it is string.

I think we like to do it properly.  To define a protobuf for Pilot to pass any type of attributes to Proxy and to Mixer

**Comment by douglas-reid** [comment]
Without the hack, we are going to end up either:
- saying no Mixer policy can be written using IP_ADDRESS (and `port`s)
- or, having policies written in an inconsistent fashion -- which will break as soon as we fix the issue.

**Comment by mandarjog** [comment]
I think the hack is necessary for 0.2, without the hack `match: destination.ip == "10.1.1.9" && source.ip == ip("10.10.10.1")` this inconsistent expression is used in our configuration.
It is a low risk hack with just a few lines of code, we should go for it.

The alternative is for Proxy to consume the `attribute-manifest` proto that is already defined in Mixer. That is the authoritative mapping between an attribute name and its type.

**Comment by geeknoid** [comment]
We definitely should do the hack for 0.2.

In the long run, the proxy should rely on the manifest data for attribute
typing contraints.

**Comment by kyessenov** [comment]
This isn't just a proxy issue. Pilot sets the value. The problem is that we can't communicate the right type from pilot to proxy.

**Comment by qiwzhang** [comment]
For 0.2,  Proxy will only convert suffix ".ip" to bytes as a hack.  Hi @kyessenov , could you check if there are other types Proxy should convert, such as  ".port"?
After 0.2, we are going to to it properly.

**Comment by qiwzhang** [comment]
BTW,  do we have ipv6 address?    Since it is a hack,   if we don't use ipv6,  I will not support it.

**Comment by kyessenov** [comment]
Sure, let's add more hacks :) There's a list of strings set to `destination.service` that might need some type conversion too, and the corresponding attributes `destination.name` and `destination.namespace`. There's no support for ipv6 yet.  These are the only attributes used by Pilot (plus matching `source.*`)

**Comment by qiwzhang** [comment]
Cool,  these attributes are string,  you don't use port yet,  so not port. not ipv6.

**Comment by cmeury** [comment]
I encountered this issue, `0.2.7` fixed it for me.

**Comment by qiwzhang** [comment]
New client config https://github.com/istio/api/blob/master/mixer/v1/config/client/client_config.proto should support it now.
