### ISSUE TITLE
Add new dependency on Mixer

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#501]
Now Mixerclient is automatically getting the latest global dictionary from mixer/API.
Proxy integration test is using both Mixerclient and Mixer.   If Mixer is not updated to use the latest global dictionary, integration test will fail.

Mixer SHA in defined in WORKSPACE.

**Comment by qiwzhang** [comment]
Please see https://github.com/istio/proxy/pull/500

**Comment by sebastienvas** [comment]
There is currently no way to force them to be in synced, however if an update is done to API, the first PR generated automatically might fail, but the remaining one will eventually success assuming that we don't have too many updates on API.

This will be fixed properly once we have flat builds.

**Comment by kyessenov** [comment]
Seems like this has also issues with circular dependencies istio-wide. Seems like this is a testing issue, can be addressed in 0.3.

**Comment by ldemailly** [comment]
can you say what is the circular dependency ?

**Comment by sebastienvas** [comment]
I am thinking of reverting my PR as each update to mixer is going to trigger a new update to proxy and therefore an update to pilot and then istio. After talking to kuat this deps only exist for testing.

**Comment by ldemailly** [comment]
let's create istio/core or similar to move common code/dependencies between mixer and pilot there ?
