### ISSUE TITLE
Building Istio Proxy on Centos 7

### ISSUE THREAD

**Issue by kaizen2017** [istio/proxy#587]
Has anyone being able to build istio proxy [https://github.com/istio/proxy/] on Centos ? 

I am continuously running into this error ? Has anyone seen this before

External dependency build failed, check above log for 
errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.

ERROR: error loading package 'src/envoy/mixer': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdpart
y/protobuf': External dep build failed.

ERROR: error loading package 'src/envoy/mixer': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdpart
y/protobuf': External dep build failed.

**Comment by lizan** [comment]
Can you paste your full log of bazel output?

**Comment by qiwzhang** [comment]
@kaizen2017 could you try the setup at the end of https://github.com/istio/proxy/issues/695?
I will close this one, will use that one for proxying building issue.
