### ISSUE TITLE
`request.size` value is always 0

### ISSUE THREAD

**Issue by douglas-reid** [istio/proxy#602]
Testing with bookinfo. All Mixer received values of `request.size` are 0. Is there an issue with calculating request size info ?

**Comment by qiwzhang** [comment]
request.size is only counting request body size. same as response.size which is only for response body size.

We are using this "bytesReceived" field from Envoy:  https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/access_log.h#L97

Not sure how easy to count HTTP headers.

**Comment by qiwzhang** [comment]
I can use this field:

https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/header_map.h#L353

**Comment by qiwzhang** [comment]
According the Istio attribute definition:  https://istio.io/docs/reference/config/mixer/attribute-vocabulary.html

request.size only counts body, not HTTP headers.

So the current implementation is correct.
