### ISSUE TITLE
JWT-AUTH and OPTIONS requests

### ISSUE THREAD

**Issue by sebastienblanc** [istio/proxy#651]
Hi,

I started to play with the `jwt-auth` and it works well, I could even integrate it with my Keycloak IDP. But now I'm trying to do a request from the browser and it fails on the `OPTIONS` preflight because the authorization header is not present (the browser remove it automatically). Is there an easy way to tell the filter to skip 'OPTIONS' requests (even if it's a bit hacky, it's for demo purposes) ?

Thx

**Comment by sebastienblanc** [comment]
So I just found a way to fix it, tbh, no idea if it's an hack or a valid fix ;) , if you think it's valid I can do a PR, 
in `FilterHeadersStatus JwtVerificationFilter::decodeHeaders` I added this : 
``` 
  const auto method = headers.Method();
  if (method == nullptr || method->value().c_str() == Http::Headers::get().MethodValues.Options) {
     return FilterHeadersStatus::Continue;
  }

```

**Comment by qiwzhang** [comment]
Should OPTIONS by-pass auth check by default?  @lizan  what do you think?

**Comment by sebastienblanc** [comment]
We could add a flag in the config like `byPassOptions` that is `true` by default ?

**Comment by qiwzhang** [comment]
That will do.  Please create a PR then.

**Comment by lizan** [comment]
or let's make an option to let it fail-open. that will be helpful for API management to let authz to do the decision.

**Comment by lizan** [comment]
@sebastienblanc actually, if you use [CORS filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/cors_filter.html) before the JWT auth, I think the OPTIONS request will not processed by this auth filter, no?

**Comment by sebastienblanc** [comment]
@lizan That was actually the first thing I tried but it didn't seems to work but it could be that I configured `cors` wrongly in the `envoy.conf` , could you maybe share a snippet of conf with me and will try again ?

**Comment by lizan** [comment]
Hmm, I don't have a working envoy.conf right now. Can you share the conf you tried, I can take a look on it.

**Comment by qiwzhang** [comment]
https://github.com/istio/proxy/pull/1183

With this change, you an bypass JWT verification for CORS traffic.

**Comment by deitrix** [comment]
@qiwzhang This PR doesn't solve the described issue, it only accounts for including/excluding paths from the Policy. This issue requires excluding a particular HTTP method, for all requests, regardless of the path.

As per the spec, CORS pre-flight requests shouldn't include user credentials:
http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

It's a common use-case that certain method/path combinations are to be treated differently from an authentication standpoint. It would be useful if the configuration allowed for the following inclusion/exclusion scenarios:
- All requests of a particular HTTP method.
- All requests of a particular HTTP method to a particular path, or path prefix.
- All requests to a particular path, or path prefix.

**Comment by qiwzhang** [comment]
@deitrix you request to bypass auth for OTPIONS makes sense.  

@lei-tang could you help?

**Comment by lei-tang** [comment]
@qiwzhang Sure.
