### ISSUE TITLE
Istio route rules that apply to istio ingress controller are being ignored

### ISSUE THREAD

**Issue by clintberry** [istio/proxy#708]
Adding route rules that apply to the istio ingress controller don't seem to work. I see this warning before it routes to the service, ignoring my rule for blocking all traffic with a 403:

`[2017-12-07 17:29:12.679][708][warning][http] src/envoy/mixer/mixer_control.cc:419] Could not convert to ip: destination.ip:`

Steps to reproduce:
1) setup brand new GKE cluster on google cloud
2) Install istio
3) Follow instructions on this page: https://istio.io/docs/tasks/traffic-management/ingress.html which basically has you install the httpbin sample app, add an ingress, and add two route rules
4) Execute the curl towards the bottom of the page to test the route rules: `curl -I http://$INGRESS_HOST/headers`

Expected behavior is to get a 403 back, but a 200 is returned and logs show the warning above.

I hope this is enough detail for an issue. If it is not, let me know and I will dig in deeper.

**Comment by clintberry** [comment]
Also, I am here at KubeCon, if you want me to come show you first hand so you don't have to set it up I would be happy to.

**Comment by qiwzhang** [comment]
It is better to move this issue to istio/istio repo.

**Comment by linsun** [comment]
seems same as https://github.com/istio/istio.github.io/issues/702

**Comment by kyessenov** [comment]
I think this could be due to one of two causes:
- faults do not apply at ingress proxy (a known and documented limitation)
- mixer unable to derive some attributes for the requests to ingress (also known bug in older releases)

thanks for the bug report!
