### ISSUE TITLE
Base64 encode binary HTTP/2 headers

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#749]
request.headers will store HTTP/2 headers for gRPC metadata.  Some HTTP/2 headers are binary.  But request.headers is a string map.   Need to base64 encode the binary header.

Also update the istio attribute doc. https://istio.io/docs/reference/config/mixer/attribute-vocabulary.html

**Comment by JimmyCYJ** [comment]
Binary headers are already base64 encoded. 
In https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md:
"Note that HTTP2 does not allow arbitrary octet sequences for header values so binary header values must be encoded using Base64 as per https://tools.ietf.org/html/rfc4648#section-4. Implementations MUST accept padded and un-padded values and should emit un-padded values. Applications define binary headers by having their names end with "-bin". Runtime libraries use this suffix to detect binary headers and properly apply base64 encoding & decoding as headers are sent and received."
