### ISSUE TITLE
Read attributes for envoy.conf and pass them to mixer

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#84]
Now the mixer filer config in the Envoy config has:

"config": {
                  "mixer_server": "localhost:9091"
          }

We can extend it as:

"config": {
   "mixer_server": "localhost:9091",
   "attributes": {
              "target.service": "foo",
             "source.name": "bar"
         }
 }

Proxy just read all of them and pass them to Mixer.   When deployment manager generating this config, it can put whatever attributes they want to pass to mixer.

With this change, we can remove code of reading from environment

**Comment by qiwzhang** [comment]
@kyessenov Will this work?

**Comment by qiwzhang** [comment]
@chowchow316 could you help with this one?

**Comment by chowchow316** [comment]
I'm starting to work on this one.

**Comment by chowchow316** [comment]
#87
