### ISSUE TITLE
Provide statistics for check and report latencies as histograms

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/proxy#893]
Add Check/Report latency stats as histograms.

**Comment by JimmyCYJ** [comment]
We can use a timer to wrap around the check/report call, as commented in https://github.com/istio/mixerclient/issues/324.

**Comment by JimmyCYJ** [comment]
@mandarjog  Question: Do you want Mixerclient to send check and report latencies to Mixer and display at Prometheus as histograms? I ask this because envoy has /stats admin endpoint which does not show histograms. The /stats admin endpoint only shows counters and gauges. For example, http_mixer_filter.total_blocking_remote_check_calls and tcp_mixer_filter.total_blocking_remote_check_calls are counters. And I would like to know the priority of this issue.

**Comment by mandarjog** [comment]
We now support mixer_check_server and mixer_report_server as two separate upstreams.
If we configure both of those clusters to point to the same endpoints, envoy will track their usage separately.

We can make these stats available (and configure them by default). I don't think we need to track this inside mixer client any more.
