### ISSUE TITLE
what difference between this proxy and envoy proxy？thx.

### ISSUE THREAD

**Issue by lixiaobing1** [istio/proxy#895]
what difference between this proxy and envoy proxy(https://github.com/envoyproxy/envoy)？
should we use this proxy or envoy proxy?

**Comment by qiwzhang** [comment]
This proxy add following two fitlers:
mixer_filter:  call Istio Mixer
auth_filter:   JWT auth token verification.

**Comment by lixiaobing1** [comment]
ok，THX
