### ISSUE TITLE
Send attributes from mixer to upstream

### ISSUE THREAD

**Issue by qiwzhang** [istio/proxy#926]
Mixer Check response may return some attributes: defined here[https://github.com/istio/api/blob/master/mixer/v1/check.proto#L78]

Proxy should send them as HTTP request headers to upstream.

**Comment by qiwzhang** [comment]
@geeknoid @mandarjog 

The question is: how should we use this field.  Should we send these attributes as HTTP headers to the backend  as; key is the header name, value as header value?

**Comment by geeknoid** [comment]
We don't have a specific use for this feature yet, so let's just leave this unused until there's a need.

**Comment by kyessenov** [comment]
This has actually been done with route directive.
