### ISSUE TITLE
Support other headers for providing the JWT

### ISSUE THREAD

**Issue by jlewi** [istio/proxy#939]
It would be nice if the JWT could be obtained from headers other than Authorization.

Google's identity aware proxy uses the header [x-goog-iap-jwt-assertion](https://cloud.google.com/iap/docs/signed-headers-howto)

**Comment by qiwzhang** [comment]
It will be supported according to this config.  https://github.com/istio/api/blob/master/mixer/v1/config/client/auth.proto#L118

**Comment by jlewi** [comment]
@qiwzhang Does this mean we will have to use Envoy as part of ISTIO to do JWT validation?

**Comment by qiwzhang** [comment]
No,  JWT_auth can be used standalone.  Please see this example [https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/sample/envoy.conf]

**Comment by jlewi** [comment]
Thank you.

**Comment by qiwzhang** [comment]
https://github.com/istio/proxy/pull/1186
