### ISSUE TITLE
Support ES256 algorithm

### ISSUE THREAD

**Issue by jlewi** [istio/proxy#941]
Google IAP uses ES256;
https://cloud.google.com/iap/docs/signed-headers-howto

Looks like currently only RS256 support is provided.

**Comment by jlewi** [comment]
I think this is the only issue blocking google/kubeflow from using Envoy for JWT validation (as opposed to using NGINX). (The other issues I've been able to work around just by forking the code and making trivial changes).

**Comment by jlewi** [comment]
Digging into the code, I think the only thing that needs to change is how we load the key.

ec.h
* Use [EC_KEY_new](https://github.com/openssl/openssl/blob/master/include/openssl/ec.h#L737) to create a new key
* Use [EC_KEY_set_public_key_affine_coordinates](https://github.com/openssl/openssl/blob/master/include/openssl/ec.h#L870) to set x and y based on the values obtained in the JWKs from IAP
* Use [EVP_PKEY_set1_EC_KEY](https://github.com/openssl/openssl/blob/4bed94f0c11ef63587c6b2edb03c3c438e221604/include/openssl/evp.h#L1028) to convert to EvpPKey
* Modify [Pubkeys::CreateFromJwksCore](https://github.com/istio/proxy/blob/master/src/envoy/auth/jwt.cc#L377) and [EvpGetter](https://github.com/istio/proxy/blob/master/src/envoy/auth/jwt.cc#L145) to use the above to actually create the key.

/cc @qiwzhang

**Comment by qiwzhang** [comment]
If we want to get it done earlier,  we welcome any contribution.  Otherwise, we will fix this.  ETA is next month.

**Comment by jlewi** [comment]
@qiwzhang Any update on the ETA for this?

**Comment by qiwzhang** [comment]
I am distracted by Istio/proxy code re-organization. This re-org is not done yet.  The feature could be delayed for a couple of months.  If you need this urgently,  could you contribute?

Or I will rise the priority and try to find someone in my team to help.

**Comment by jlewi** [comment]
We need this urgently. This is critical for us having a secure ingress story.

Does the [comment above](https://github.com/istio/proxy/issues/941#issuecomment-360350132) seem approximately correct in terms of what's needed?

Would you mind trying to find someone on your team and if that doesn't work we will try to carve out cycles to work on this.

**Comment by qiwzhang** [comment]
OK,  I will see if I can find someone with spare circle.
