### ISSUE TITLE
JWT Auth Filter doesn't support array type audience

### ISSUE THREAD

**Issue by sreetummidi** [istio/proxy#985]
Hello,

I have set CloudFoundry UAA (https://github.com/cloudfoundry/uaa) as the JWT  Issuer  using the policy type of kind: EndUserAuthenticationPolicySpec

I am seeing the following error in the istio proxy logs

2018-02-01T09:15:08.109839Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster productpage --service-node sidecar~172.17.0.15~productpage-v1-648bf6f798-2j6cd.default~default.svc.cluster.local --max-obj-name-len 189 -l off]
}terminate called after throwing an instance of 'Envoy::Json::Exception'
  what():  key 'aud' missing or not a string from lines 1-1

The OIDC core spec suggests that the audience can be an array if multiple audiences are present
From the spec: 

aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

Can you please address the code to handle a string array for audience in JWT and not throw an exception

Thanks,
Sree

**Comment by sreetummidi** [comment]
Spec Below

apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata:
  name: productpage
  namespace: default
spec:
  jwts:
  - issuer: https://uaa.run.pivotal.io/oauth/token
    audiences:
    - apps_manager_js
    jwks_uri: https://login.run.pivotal.io/token_key
---
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: productpage
  namespace: default
spec:
  policies:
  - name: productpage
    namespace: default
  services:
  - name: productpage
    namespace: default
---


Decode JWT


{
  "sub": "*************",
  "previous_logon_time": 1517609434561,
  "user_name": "*********",
  "origin": "uaa",
  "amr": [
    "pwd"
  ],
  "iss": "https://uaa.run.pivotal.io/oauth/token",
  "client_id": "apps_manager_js",
  "aud": [
    "apps_manager_js"
  ],
  "zid": "uaa",
  "user_id": "***********",
  "azp": "apps_manager_js",
  "scope": [
    "openid"
  ],
  "auth_time": 1517609687,
  "exp": 1517638487,
  "iat": 1517609687,
  "jti": "ec56fba8069d41cda690e091743314d8",
  "email": "*********",
  "rev_sig": "******",
  "cid": "apps_manager_js"
}

**Comment by qiwzhang** [comment]
I see.  The problem is not in the config.   but in your JWT token.   We only expect one.

The code is here  https://github.com/istio/proxy/blob/master/src/envoy/auth/jwt.cc#L280

We will fix it
